// Combined impact script for the 9 ported KOTOR 2 Force Powers (Revitalize,
// Force Scream, Force Barrier -- all 3 tiers each). Generated by
// scripts/patch_tsl_powers.py. One shared resref instead of 9: these are a
// standing feature of this build (granted automatically every launch, see
// ap_extender.c's ap_bootstrap_tsl_force_powers()), not a per-seed AP pilot.
#include "kse"

void Revive(object oCaster, object oTarget, int nHeal)
{
    SignalEvent(oTarget, EventSpellCastAt(oCaster, GetSpellId(), FALSE));
    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectResurrection(), oTarget);
    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectHeal(nHeal), oTarget);
    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectVisualEffect(VFX_IMP_HEAL), oTarget);
}

void main()
{
    int nSid = GetSpellId();
    if (nSid == 136)
    {
        // K1 port of KOTOR 2's FORCE_POWER_FORCE_SCREAM (k_inc_force.nss, DJS-OEI 12/30/2003).
        // K2's dedicated scream VFX (9005-9007) don't exist in K1's visualeffects.2da;
        // VFX_FNF_FORCE_WAVE is the closest shipped K1 burst.
        object oCaster = OBJECT_SELF;
        int nDC = GetSpellSaveDC();
        location lTarget = GetLocation(GetSpellTarget());
        int nHit = 0;
        ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectVisualEffect(VFX_FNF_FORCE_WAVE), oCaster);
        object oTarget = GetFirstObjectInShape(SHAPE_SPELLCONE, 20.0, lTarget, TRUE, OBJECT_TYPE_CREATURE);
        while (GetIsObjectValid(oTarget))
        {
            if (oTarget != oCaster && GetIsEnemy(oTarget, oCaster) && GetRacialType(oTarget) != RACIAL_TYPE_DROID)
            {
                SignalEvent(oTarget, EventSpellCastAt(oCaster, GetSpellId(), TRUE));
                int nDamage = d6(3);
                if (WillSave(oTarget, nDC, SAVING_THROW_TYPE_SONIC, oCaster) == 0)
                {
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage, DAMAGE_TYPE_SONIC), oTarget);
effect eOld = GetFirstEffect(oTarget);
        while (GetIsEffectValid(eOld))
        {
            int nOldSid = GetEffectSpellId(eOld);
            if (nOldSid == 136 || nOldSid == 137 || nOldSid == 138) RemoveEffect(oTarget, eOld);
            eOld = GetNextEffect(oTarget);
        }
                    effect eAttr = EffectAbilityDecrease(ABILITY_STRENGTH, 2);
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_DEXTERITY, 2));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_CONSTITUTION, 2));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_INTELLIGENCE, 2));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_WISDOM, 2));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_CHARISMA, 2));
                    ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eAttr, oTarget, 30.0);
                }
                else
                {
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage / 2, DAMAGE_TYPE_SONIC), oTarget);
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectForceResisted(oCaster), oTarget);
                }
                nHit++;
            }
            oTarget = GetNextObjectInShape(SHAPE_SPELLCONE, 20.0, lTarget, TRUE, OBJECT_TYPE_CREATURE);
        }
        KSE_Diag(151, "AP|FORCEPOWER|scream|tier=1|targets=" + IntToString(nHit));
    }
    else if (nSid == 137)
    {
        // K1 port of KOTOR 2's FORCE_POWER_IMPROVED_FORCE_SCREAM (k_inc_force.nss, DJS-OEI 12/30/2003).
        // K2's dedicated scream VFX (9005-9007) don't exist in K1's visualeffects.2da;
        // VFX_FNF_FORCE_WAVE is the closest shipped K1 burst.
        object oCaster = OBJECT_SELF;
        int nDC = GetSpellSaveDC();
        location lTarget = GetLocation(GetSpellTarget());
        int nHit = 0;
        ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectVisualEffect(VFX_FNF_FORCE_WAVE), oCaster);
        object oTarget = GetFirstObjectInShape(SHAPE_SPELLCONE, 20.0, lTarget, TRUE, OBJECT_TYPE_CREATURE);
        while (GetIsObjectValid(oTarget))
        {
            if (oTarget != oCaster && GetIsEnemy(oTarget, oCaster) && GetRacialType(oTarget) != RACIAL_TYPE_DROID)
            {
                SignalEvent(oTarget, EventSpellCastAt(oCaster, GetSpellId(), TRUE));
                int nDamage = d6(5);
                if (WillSave(oTarget, nDC, SAVING_THROW_TYPE_SONIC, oCaster) == 0)
                {
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage, DAMAGE_TYPE_SONIC), oTarget);
effect eOld = GetFirstEffect(oTarget);
        while (GetIsEffectValid(eOld))
        {
            int nOldSid = GetEffectSpellId(eOld);
            if (nOldSid == 136 || nOldSid == 137 || nOldSid == 138) RemoveEffect(oTarget, eOld);
            eOld = GetNextEffect(oTarget);
        }
                    effect eAttr = EffectAbilityDecrease(ABILITY_STRENGTH, 4);
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_DEXTERITY, 4));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_CONSTITUTION, 4));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_INTELLIGENCE, 4));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_WISDOM, 4));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_CHARISMA, 4));
                    ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eAttr, oTarget, 30.0);
                }
                else
                {
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage / 2, DAMAGE_TYPE_SONIC), oTarget);
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectForceResisted(oCaster), oTarget);
                }
                nHit++;
            }
            oTarget = GetNextObjectInShape(SHAPE_SPELLCONE, 20.0, lTarget, TRUE, OBJECT_TYPE_CREATURE);
        }
        KSE_Diag(151, "AP|FORCEPOWER|scream|tier=2|targets=" + IntToString(nHit));
    }
    else if (nSid == 138)
    {
        // K1 port of KOTOR 2's FORCE_POWER_MASTER_FORCE_SCREAM (k_inc_force.nss, DJS-OEI 12/30/2003).
        // K2's dedicated scream VFX (9005-9007) don't exist in K1's visualeffects.2da;
        // VFX_FNF_FORCE_WAVE is the closest shipped K1 burst.
        object oCaster = OBJECT_SELF;
        int nDC = GetSpellSaveDC();
        location lTarget = GetLocation(oCaster);
        int nHit = 0;
        ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectVisualEffect(VFX_FNF_FORCE_WAVE), oCaster);
        object oTarget = GetFirstObjectInShape(SHAPE_SPHERE, 12.0, lTarget, TRUE, OBJECT_TYPE_CREATURE);
        while (GetIsObjectValid(oTarget))
        {
            if (oTarget != oCaster && GetIsEnemy(oTarget, oCaster) && GetRacialType(oTarget) != RACIAL_TYPE_DROID)
            {
                SignalEvent(oTarget, EventSpellCastAt(oCaster, GetSpellId(), TRUE));
                int nDamage = d6(7);
                if (WillSave(oTarget, nDC, SAVING_THROW_TYPE_SONIC, oCaster) == 0)
                {
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage, DAMAGE_TYPE_SONIC), oTarget);
effect eOld = GetFirstEffect(oTarget);
        while (GetIsEffectValid(eOld))
        {
            int nOldSid = GetEffectSpellId(eOld);
            if (nOldSid == 136 || nOldSid == 137 || nOldSid == 138) RemoveEffect(oTarget, eOld);
            eOld = GetNextEffect(oTarget);
        }
                    effect eAttr = EffectAbilityDecrease(ABILITY_STRENGTH, 6);
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_DEXTERITY, 6));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_CONSTITUTION, 6));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_INTELLIGENCE, 6));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_WISDOM, 6));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_CHARISMA, 6));
                    ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eAttr, oTarget, 30.0);
                }
                else
                {
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage / 2, DAMAGE_TYPE_SONIC), oTarget);
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectForceResisted(oCaster), oTarget);
                }
                nHit++;
            }
            oTarget = GetNextObjectInShape(SHAPE_SPHERE, 12.0, lTarget, TRUE, OBJECT_TYPE_CREATURE);
        }
        KSE_Diag(151, "AP|FORCEPOWER|scream|tier=3|targets=" + IntToString(nHit));
    }
    else if (nSid == 142)
    {
        // K1 port of KOTOR 2's FORCE_POWER_MASTER_ENERGY_RESISTANCE
        // (k_inc_force.nss, DJS-OEI 12/9-10/2003). Self-only, unlike K2's
        // real script (which also buffs the whole party for a PC caster)
        // -- kept consistent with K1's own Resist Energy 1/2, which are
        // both self-only, rather than introducing new party-wide scope
        // for what's meant to be a small, single-tier addition.
        object oCaster = OBJECT_SELF;
effect eOld = GetFirstEffect(oCaster);
        while (GetIsEffectValid(eOld))
        {
            int nOldSid = GetEffectSpellId(eOld);
            if (nOldSid == 142) RemoveEffect(oCaster, eOld);
            eOld = GetNextEffect(oCaster);
        }
        effect eLink = EffectDamageResistance(DAMAGE_TYPE_COLD, 20);
        eLink = EffectLinkEffects(eLink, EffectDamageResistance(DAMAGE_TYPE_FIRE, 20));
        eLink = EffectLinkEffects(eLink, EffectDamageResistance(DAMAGE_TYPE_SONIC, 20));
        eLink = EffectLinkEffects(eLink, EffectDamageResistance(DAMAGE_TYPE_BLASTER, 20));
        eLink = EffectLinkEffects(eLink, EffectDamageResistance(DAMAGE_TYPE_ELECTRICAL, 20));
        effect eVis = EffectVisualEffect(VFX_PRO_RESIST_ELEMENTS);
        ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eLink, oCaster, 120.0);
        ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eVis, oCaster, 1.0);
        KSE_Diag(151, "AP|FORCEPOWER|energy_resistance|dr=20|dur=120");
    }
    else if (nSid == 143)
    {
        // K1 port of KOTOR 2's FORCE_POWER_MASTER_HEAL (k_inc_force.nss,
        // "Same as Improved Heal with addition 5 VP and Stun removal").
        // Party-wide like Revitalize -- heals the caster plus every valid
        // party member. Formula is K2's own active code path verbatim
        // (its Form/Stance multiplier branch is commented out in K2's
        // own shipped source too, so nMultiplier is always 1 there).
        object oCaster = OBJECT_SELF;
effect eOld = GetFirstEffect(oCaster);
        while (GetIsEffectValid(eOld))
        {
            int nOldSid = GetEffectSpellId(eOld);
            if (nOldSid == 143) RemoveEffect(oCaster, eOld);
            eOld = GetNextEffect(oCaster);
        }
        int nHeal = GetAbilityModifier(ABILITY_WISDOM, oCaster) + GetAbilityModifier(ABILITY_CHARISMA, oCaster)
                  + 15 + 2 * GetHitDice(oCaster);
        int i;
        for (i = 0; i < 3; i++)
        {
            object oPM = GetPartyMemberByIndex(i);
            if (GetIsObjectValid(oPM))
            {
effect eOld = GetFirstEffect(oPM);
        while (GetIsEffectValid(eOld))
        {
            int nOldSid = GetEffectSpellId(eOld);
            if (nOldSid == 143) RemoveEffect(oPM, eOld);
            eOld = GetNextEffect(oPM);
        }
                ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectHeal(nHeal), oPM);
                effect eStun = GetFirstEffect(oPM);
                while (GetIsEffectValid(eStun))
                {
                    if (GetEffectType(eStun) == EFFECT_TYPE_STUNNED) RemoveEffect(oPM, eStun);
                    eStun = GetNextEffect(oPM);
                }
                ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectVisualEffect(VFX_IMP_HEAL), oPM);
            }
        }
        KSE_Diag(151, "AP|FORCEPOWER|master_heal|amount=" + IntToString(nHeal));
    }
}
