// Combined impact script for the 9 ported KOTOR 2 Force Powers (Revitalize,
// Force Scream, Force Barrier -- all 3 tiers each). Generated by
// scripts/patch_tsl_powers.py. One shared resref instead of 9: these are a
// standing feature of this build (granted automatically every launch, see
// ap_extender.c's ap_bootstrap_tsl_force_powers()), not a per-seed AP pilot.
#include "kse"

void Revive(object oCaster, object oTarget, int nHeal)
{
    SignalEvent(oTarget, EventSpellCastAt(oCaster, GetSpellId(), FALSE));
    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectResurrection(), oTarget);
    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectHeal(nHeal), oTarget);
    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectVisualEffect(VFX_IMP_HEAL), oTarget);
}

void main()
{
    int nSid = GetSpellId();
    if (nSid == 133)
    {
        // K1 port of KOTOR 2's FORCE_POWER_REVITALIZE (k_inc_force.nss, DJS-OEI 1/2/2004;
        // fixed heal amounts per RWT-OEI 09/27/04 FMP#4893). Same EffectResurrection+
        // EffectHeal shape the K1FPP mod's Revitalise already proved works in K1.
        object oCaster = OBJECT_SELF;
        int nRevived = 0;
        if (!IsObjectPartyMember(oCaster)) return;
        object oBest = OBJECT_INVALID;
        float fBest = 999999.0;
        int i;
        for (i = 0; i < 3; i++)
        {
            object oPM = GetPartyMemberByIndex(i);
            if (GetIsObjectValid(oPM) && oPM != oCaster && GetRacialType(oPM) != RACIAL_TYPE_DROID
                && GetCurrentHitPoints(oPM) < 1)
            {
                float fDist = GetDistanceBetween(oCaster, oPM);
                if (fDist < fBest) { fBest = fDist; oBest = oPM; }
            }
        }
        if (GetIsObjectValid(oBest)) { Revive(oCaster, oBest, 10); nRevived++; }
        KSE_Diag(151, "AP|FORCEPOWER|revitalize|tier=1|revived=" + IntToString(nRevived));
    }
    else if (nSid == 134)
    {
        // K1 port of KOTOR 2's FORCE_POWER_IMPROVED_REVITALIZE (k_inc_force.nss, DJS-OEI 1/2/2004;
        // fixed heal amounts per RWT-OEI 09/27/04 FMP#4893). Same EffectResurrection+
        // EffectHeal shape the K1FPP mod's Revitalise already proved works in K1.
        object oCaster = OBJECT_SELF;
        int nRevived = 0;
        if (!IsObjectPartyMember(oCaster)) return;
        int i;
        for (i = 0; i < 3; i++)
        {
            object oPM = GetPartyMemberByIndex(i);
            if (GetIsObjectValid(oPM) && oPM != oCaster && GetRacialType(oPM) != RACIAL_TYPE_DROID
                && GetCurrentHitPoints(oPM) < 1)
            {
                Revive(oCaster, oPM, 25);
                nRevived++;
            }
        }
        KSE_Diag(151, "AP|FORCEPOWER|revitalize|tier=2|revived=" + IntToString(nRevived));
    }
    else if (nSid == 135)
    {
        // K1 port of KOTOR 2's FORCE_POWER_MASTER_REVITALIZE (k_inc_force.nss, DJS-OEI 1/2/2004;
        // fixed heal amounts per RWT-OEI 09/27/04 FMP#4893). Same EffectResurrection+
        // EffectHeal shape the K1FPP mod's Revitalise already proved works in K1.
        object oCaster = OBJECT_SELF;
        int nRevived = 0;
        if (!IsObjectPartyMember(oCaster)) return;
        int i;
        for (i = 0; i < 3; i++)
        {
            object oPM = GetPartyMemberByIndex(i);
            if (GetIsObjectValid(oPM) && oPM != oCaster && GetRacialType(oPM) != RACIAL_TYPE_DROID
                && GetCurrentHitPoints(oPM) < 1)
            {
                Revive(oCaster, oPM, 50);
                nRevived++;
            }
        }
        KSE_Diag(151, "AP|FORCEPOWER|revitalize|tier=3|revived=" + IntToString(nRevived));
    }
    else if (nSid == 136)
    {
        // K1 port of KOTOR 2's FORCE_POWER_FORCE_SCREAM (k_inc_force.nss, DJS-OEI 12/30/2003).
        // K2's dedicated scream VFX (9005-9007) don't exist in K1's visualeffects.2da;
        // VFX_FNF_FORCE_WAVE is the closest shipped K1 burst.
        object oCaster = OBJECT_SELF;
        int nDC = GetSpellSaveDC();
        location lTarget = GetLocation(GetSpellTarget());
        int nHit = 0;
        ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectVisualEffect(VFX_FNF_FORCE_WAVE), oCaster);
        object oTarget = GetFirstObjectInShape(SHAPE_SPELLCONE, 20.0, lTarget, TRUE, OBJECT_TYPE_CREATURE);
        while (GetIsObjectValid(oTarget))
        {
            if (oTarget != oCaster && GetIsEnemy(oTarget, oCaster) && GetRacialType(oTarget) != RACIAL_TYPE_DROID)
            {
                SignalEvent(oTarget, EventSpellCastAt(oCaster, GetSpellId(), TRUE));
                int nDamage = d6(3);
                if (WillSave(oTarget, nDC, SAVING_THROW_TYPE_SONIC, oCaster) == 0)
                {
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage, DAMAGE_TYPE_SONIC), oTarget);
effect eOld = GetFirstEffect(oTarget);
        while (GetIsEffectValid(eOld))
        {
            int nOldSid = GetEffectSpellId(eOld);
            if (nOldSid == 136 || nOldSid == 137 || nOldSid == 138) RemoveEffect(oTarget, eOld);
            eOld = GetNextEffect(oTarget);
        }
                    effect eAttr = EffectAbilityDecrease(ABILITY_STRENGTH, 2);
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_DEXTERITY, 2));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_CONSTITUTION, 2));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_INTELLIGENCE, 2));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_WISDOM, 2));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_CHARISMA, 2));
                    ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eAttr, oTarget, 30.0);
                }
                else
                {
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage / 2, DAMAGE_TYPE_SONIC), oTarget);
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectForceResisted(oCaster), oTarget);
                }
                nHit++;
            }
            oTarget = GetNextObjectInShape(SHAPE_SPELLCONE, 20.0, lTarget, TRUE, OBJECT_TYPE_CREATURE);
        }
        KSE_Diag(151, "AP|FORCEPOWER|scream|tier=1|targets=" + IntToString(nHit));
    }
    else if (nSid == 137)
    {
        // K1 port of KOTOR 2's FORCE_POWER_IMPROVED_FORCE_SCREAM (k_inc_force.nss, DJS-OEI 12/30/2003).
        // K2's dedicated scream VFX (9005-9007) don't exist in K1's visualeffects.2da;
        // VFX_FNF_FORCE_WAVE is the closest shipped K1 burst.
        object oCaster = OBJECT_SELF;
        int nDC = GetSpellSaveDC();
        location lTarget = GetLocation(GetSpellTarget());
        int nHit = 0;
        ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectVisualEffect(VFX_FNF_FORCE_WAVE), oCaster);
        object oTarget = GetFirstObjectInShape(SHAPE_SPELLCONE, 20.0, lTarget, TRUE, OBJECT_TYPE_CREATURE);
        while (GetIsObjectValid(oTarget))
        {
            if (oTarget != oCaster && GetIsEnemy(oTarget, oCaster) && GetRacialType(oTarget) != RACIAL_TYPE_DROID)
            {
                SignalEvent(oTarget, EventSpellCastAt(oCaster, GetSpellId(), TRUE));
                int nDamage = d6(5);
                if (WillSave(oTarget, nDC, SAVING_THROW_TYPE_SONIC, oCaster) == 0)
                {
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage, DAMAGE_TYPE_SONIC), oTarget);
effect eOld = GetFirstEffect(oTarget);
        while (GetIsEffectValid(eOld))
        {
            int nOldSid = GetEffectSpellId(eOld);
            if (nOldSid == 136 || nOldSid == 137 || nOldSid == 138) RemoveEffect(oTarget, eOld);
            eOld = GetNextEffect(oTarget);
        }
                    effect eAttr = EffectAbilityDecrease(ABILITY_STRENGTH, 4);
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_DEXTERITY, 4));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_CONSTITUTION, 4));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_INTELLIGENCE, 4));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_WISDOM, 4));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_CHARISMA, 4));
                    ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eAttr, oTarget, 30.0);
                }
                else
                {
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage / 2, DAMAGE_TYPE_SONIC), oTarget);
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectForceResisted(oCaster), oTarget);
                }
                nHit++;
            }
            oTarget = GetNextObjectInShape(SHAPE_SPELLCONE, 20.0, lTarget, TRUE, OBJECT_TYPE_CREATURE);
        }
        KSE_Diag(151, "AP|FORCEPOWER|scream|tier=2|targets=" + IntToString(nHit));
    }
    else if (nSid == 138)
    {
        // K1 port of KOTOR 2's FORCE_POWER_MASTER_FORCE_SCREAM (k_inc_force.nss, DJS-OEI 12/30/2003).
        // K2's dedicated scream VFX (9005-9007) don't exist in K1's visualeffects.2da;
        // VFX_FNF_FORCE_WAVE is the closest shipped K1 burst.
        object oCaster = OBJECT_SELF;
        int nDC = GetSpellSaveDC();
        location lTarget = GetLocation(oCaster);
        int nHit = 0;
        ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectVisualEffect(VFX_FNF_FORCE_WAVE), oCaster);
        object oTarget = GetFirstObjectInShape(SHAPE_SPHERE, 12.0, lTarget, TRUE, OBJECT_TYPE_CREATURE);
        while (GetIsObjectValid(oTarget))
        {
            if (oTarget != oCaster && GetIsEnemy(oTarget, oCaster) && GetRacialType(oTarget) != RACIAL_TYPE_DROID)
            {
                SignalEvent(oTarget, EventSpellCastAt(oCaster, GetSpellId(), TRUE));
                int nDamage = d6(7);
                if (WillSave(oTarget, nDC, SAVING_THROW_TYPE_SONIC, oCaster) == 0)
                {
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage, DAMAGE_TYPE_SONIC), oTarget);
effect eOld = GetFirstEffect(oTarget);
        while (GetIsEffectValid(eOld))
        {
            int nOldSid = GetEffectSpellId(eOld);
            if (nOldSid == 136 || nOldSid == 137 || nOldSid == 138) RemoveEffect(oTarget, eOld);
            eOld = GetNextEffect(oTarget);
        }
                    effect eAttr = EffectAbilityDecrease(ABILITY_STRENGTH, 6);
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_DEXTERITY, 6));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_CONSTITUTION, 6));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_INTELLIGENCE, 6));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_WISDOM, 6));
                    eAttr = EffectLinkEffects(eAttr, EffectAbilityDecrease(ABILITY_CHARISMA, 6));
                    ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eAttr, oTarget, 30.0);
                }
                else
                {
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage / 2, DAMAGE_TYPE_SONIC), oTarget);
                    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectForceResisted(oCaster), oTarget);
                }
                nHit++;
            }
            oTarget = GetNextObjectInShape(SHAPE_SPHERE, 12.0, lTarget, TRUE, OBJECT_TYPE_CREATURE);
        }
        KSE_Diag(151, "AP|FORCEPOWER|scream|tier=3|targets=" + IntToString(nHit));
    }
    else if (nSid == 139)
    {
        // K1 port of KOTOR 2's FORCE_POWER_FORCE_BARRIER (k_inc_force.nss, DJS-OEI 12/11/2003).
        object oCaster = OBJECT_SELF;
effect eOld = GetFirstEffect(oCaster);
        while (GetIsEffectValid(eOld))
        {
            int nOldSid = GetEffectSpellId(eOld);
            if (nOldSid == 139 || nOldSid == 140 || nOldSid == 141) RemoveEffect(oCaster, eOld);
            eOld = GetNextEffect(oCaster);
        }
        effect eLink = EffectDamageResistance(DAMAGE_TYPE_BLUDGEONING, 4);
        eLink = EffectLinkEffects(eLink, EffectDamageResistance(DAMAGE_TYPE_PIERCING, 4));
        eLink = EffectLinkEffects(eLink, EffectDamageResistance(DAMAGE_TYPE_SLASHING, 4));
        effect eVis = EffectVisualEffect(VFX_PRO_FORCE_ARMOR);
        eVis = EffectLinkEffects(eVis, EffectVisualEffect(VFX_PRO_FORCE_SHIELD));
        ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eLink, oCaster, 30.0);
        ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eVis, oCaster, 3.0);
        KSE_Diag(151, "AP|FORCEPOWER|barrier|tier=1|dr=4|dur=30");
    }
    else if (nSid == 140)
    {
        // K1 port of KOTOR 2's FORCE_POWER_IMPROVED_FORCE_BARRIER (k_inc_force.nss, DJS-OEI 12/11/2003).
        object oCaster = OBJECT_SELF;
effect eOld = GetFirstEffect(oCaster);
        while (GetIsEffectValid(eOld))
        {
            int nOldSid = GetEffectSpellId(eOld);
            if (nOldSid == 139 || nOldSid == 140 || nOldSid == 141) RemoveEffect(oCaster, eOld);
            eOld = GetNextEffect(oCaster);
        }
        effect eLink = EffectDamageResistance(DAMAGE_TYPE_BLUDGEONING, 8);
        eLink = EffectLinkEffects(eLink, EffectDamageResistance(DAMAGE_TYPE_PIERCING, 8));
        eLink = EffectLinkEffects(eLink, EffectDamageResistance(DAMAGE_TYPE_SLASHING, 8));
        effect eVis = EffectVisualEffect(VFX_PRO_FORCE_ARMOR);
        eVis = EffectLinkEffects(eVis, EffectVisualEffect(VFX_PRO_FORCE_SHIELD));
        ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eLink, oCaster, 45.0);
        ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eVis, oCaster, 3.0);
        KSE_Diag(151, "AP|FORCEPOWER|barrier|tier=2|dr=8|dur=45");
    }
    else if (nSid == 141)
    {
        // K1 port of KOTOR 2's FORCE_POWER_MASTER_FORCE_BARRIER (k_inc_force.nss, DJS-OEI 12/11/2003).
        object oCaster = OBJECT_SELF;
effect eOld = GetFirstEffect(oCaster);
        while (GetIsEffectValid(eOld))
        {
            int nOldSid = GetEffectSpellId(eOld);
            if (nOldSid == 139 || nOldSid == 140 || nOldSid == 141) RemoveEffect(oCaster, eOld);
            eOld = GetNextEffect(oCaster);
        }
        effect eLink = EffectDamageResistance(DAMAGE_TYPE_BLUDGEONING, 15);
        eLink = EffectLinkEffects(eLink, EffectDamageResistance(DAMAGE_TYPE_PIERCING, 15));
        eLink = EffectLinkEffects(eLink, EffectDamageResistance(DAMAGE_TYPE_SLASHING, 15));
        effect eVis = EffectVisualEffect(VFX_PRO_FORCE_ARMOR);
        eVis = EffectLinkEffects(eVis, EffectVisualEffect(VFX_PRO_FORCE_SHIELD));
        ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eLink, oCaster, 60.0);
        ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eVis, oCaster, 3.0);
        KSE_Diag(151, "AP|FORCEPOWER|barrier|tier=3|dr=15|dur=60");
    }
}
