// AUTO-GENERATED by scripts/generate_poll_shared.py -- do not hand-edit.
// The single shared 'brain' script every area trampoline calls via
// ExecuteScript("ap_poll_shared", OBJECT_SELF). Editing/recompiling THIS
// file is the only redevelopment cost for new checks -- the 97 area
// trampolines that call it never need to change.
#include "kse"

// Area-visited checks are done INLINE in each area trampoline, not here --
// a global set immediately before ExecuteScript was confirmed NOT visible
// to the called script in this engine build (true for both string and
// number globals). See generate_area_trampolines.py for the area-check
// logic and PHASE10 notes for the full writeup.

// NOTE: custom (non-globalcat.2da) global variable names were confirmed
// this session to NOT persist in this engine build -- SetGlobalBoolean/
// SetGlobalNumber on any made-up name silently fails to stick, even
// same-tick in the cleanest possible test. So none of the checks below
// use custom globals for dedup/seen-tracking any more -- they report
// UNCONDITIONALLY every poll whenever the real, engine-native condition
// (a real globalcat.2da quest flag, IsAvailableCreature, current XP) is
// true. Deduplication now lives on the extender/AP-client side, which has
// real, uncapped persistent storage -- not in the game scripts.
void CheckQuests()
{
    if (GetGlobalBoolean("DAN_STARMAP_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_STARMAP_DONE");
    }
    if (GetGlobalBoolean("DAN_JUHANI_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_JUHANI_DONE");
    }
    if (GetGlobalBoolean("DAN_VANDARJ_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VANDARJ_DONE");
    }
    if (GetGlobalBoolean("DAN_VANDARS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VANDARS_DONE");
    }
    if (GetGlobalBoolean("DAN_VANDARR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VANDARR_DONE");
    }
    if (GetGlobalBoolean("DAN_ZHARJ_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ZHARJ_DONE");
    }
    if (GetGlobalBoolean("DAN_ZHARL_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ZHARL_DONE");
    }
    if (GetGlobalBoolean("DAN_CRATISJ_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_CRATISJ_DONE");
    }
    if (GetGlobalBoolean("DAN_CRATISL_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_CRATISL_DONE");
    }
    if (GetGlobalBoolean("DAN_KARAL_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_KARAL_DONE");
    }
    if (GetGlobalBoolean("DAN_AHLAN_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_AHLAN_DONE");
    }
    if (GetGlobalBoolean("DAN_ESTATE_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ESTATE_DONE");
    }
    if (GetGlobalBoolean("DAN_WHITE_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_WHITE_DONE");
    }
    if (GetGlobalBoolean("DAN_BLACK_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_BLACK_DONE");
    }
    if (GetGlobalBoolean("DAN_MEET_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_MEET_DONE");
    }
    if (GetGlobalBoolean("DAN_HATE_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_HATE_DONE");
    }
    if (GetGlobalBoolean("DAN_SHEN_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_SHEN_DONE");
    }
    if (GetGlobalBoolean("DAN_LEAVE_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_LEAVE_DONE");
    }
    if (GetGlobalBoolean("DAN_VISION_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VISION_DONE");
    }
    if (GetGlobalBoolean("DAN_CRYSTAL_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_CRYSTAL_DONE");
    }
    if (GetGlobalBoolean("DAN_PLAINS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_PLAINS_DONE");
    }
    if (GetGlobalBoolean("DAN_DOOR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_DOOR_DONE");
    }
    if (GetGlobalBoolean("DAN_BELAYAS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_BELAYAS_DONE");
    }
    if (GetGlobalBoolean("DAN_BELAYAT_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_BELAYAT_DONE");
    }
    if (GetGlobalBoolean("DAN_BELAYAJ_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_BELAYAJ_DONE");
    }
    if (GetGlobalBoolean("DAN_DROID_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_DROID_DONE");
    }
    if (GetGlobalBoolean("DAN_CRATISF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_CRATISF_DONE");
    }
    if (GetGlobalBoolean("DAN_CRATISS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_CRATISS_DONE");
    }
    if (GetGlobalBoolean("DAN_KARALF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_KARALF_DONE");
    }
    if (GetGlobalBoolean("DAN_ESTATEC_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ESTATEC_DONE");
    }
    if (GetGlobalBoolean("DAN_JUHANIQ_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_JUHANIQ_DONE");
    }
    if (GetGlobalBoolean("DAN_COMMENT_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_COMMENT_DONE");
    }
    if (GetGlobalBoolean("DAN_DROIDS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_DROIDS_DONE");
    }
    if (GetGlobalBoolean("DAN_BODY_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_BODY_DONE");
    }
    if (GetGlobalBoolean("DAN_MISSC_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_MISSC_DONE");
    }
    if (GetGlobalBoolean("DAN_MISSB_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_MISSB_DONE");
    }
    if (GetGlobalBoolean("DAN_ZAALK_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ZAALK_DONE");
    }
    if (GetGlobalBoolean("DAN_BELAYAM_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_BELAYAM_DONE");
    }
    if (GetGlobalBoolean("DAN_MEETS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_MEETS_DONE");
    }
    if (GetGlobalBoolean("DAN_VANDARP_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VANDARP_DONE");
    }
    if (GetGlobalBoolean("DAN_ZHARD_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ZHARD_DONE");
    }
    if (GetGlobalBoolean("DAN_ZHARC_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ZHARC_DONE");
    }
    if (GetGlobalBoolean("DAN_ZHARH_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ZHARH_DONE");
    }
    if (GetGlobalBoolean("DAN_VROOKJ_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VROOKJ_DONE");
    }
    if (GetGlobalBoolean("DAN_VROOKR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VROOKR_DONE");
    }
    if (GetGlobalBoolean("DAN_VROOKP_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VROOKP_DONE");
    }
    if (GetGlobalBoolean("DAN_NEMOF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_NEMOF_DONE");
    }
    if (GetGlobalBoolean("DAN_NEMOJ_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_NEMOJ_DONE");
    }
    if (GetGlobalBoolean("DAN_NEMOR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_NEMOR_DONE");
    }
    if (GetGlobalBoolean("DAN_CRATISI_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_CRATISI_DONE");
    }
    if (GetGlobalBoolean("DAN_SOLD_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_SOLD_DONE");
    }
    if (GetGlobalBoolean("DAN_EGGS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_EGGS_DONE");
    }
    if (GetGlobalBoolean("DAN_GARF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_GARF_DONE");
    }
    if (GetGlobalBoolean("DAN_GARL_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_GARL_DONE");
    }
    if (GetGlobalBoolean("MAN_DAKOTAF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_DAKOTAF_DONE");
    }
    if (GetGlobalBoolean("MAN_DUANF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_DUANF_DONE");
    }
    if (GetGlobalBoolean("MAN_ECHANIR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_ECHANIR_DONE");
    }
    if (GetGlobalBoolean("MAN_ECHANIF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_ECHANIF_DONE");
    }
    if (GetGlobalBoolean("MAN_ARBITER_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_ARBITER_DONE");
    }
    if (GetGlobalBoolean("MAN_ELORAFN_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_ELORAFN_DONE");
    }
    if (GetGlobalBoolean("MAN_FIRITHR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_FIRITHR_DONE");
    }
    if (GetGlobalBoolean("MAN_RODIANF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_RODIANF_DONE");
    }
    if (GetGlobalBoolean("MAN_ECHANIT_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_ECHANIT_DONE");
    }
    if (GetGlobalBoolean("MAN_GONTOR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_GONTOR_DONE");
    }
    if (GetGlobalBoolean("MAN_MANDAL_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_MANDAL_DONE");
    }
    if (GetGlobalBoolean("MAN_NILKOF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_NILKOF_DONE");
    }
    if (GetGlobalBoolean("MAN_NILKOQ_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_NILKOQ_DONE");
    }
    if (GetGlobalBoolean("MAN_PORTF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_PORTF_DONE");
    }
    if (GetGlobalBoolean("MAN_REPDIQ_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_REPDIQ_DONE");
    }
    if (GetGlobalBoolean("MAN_REPRET_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_REPRET_DONE");
    }
    if (GetGlobalBoolean("MAN_TYVARKT_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_TYVARKT_DONE");
    }
    if (GetGlobalBoolean("MAN_REPSPYC_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_REPSPYC_DONE");
    }
    if (GetGlobalBoolean("MAN_CRIME_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_CRIME_DONE");
    }
    if (GetGlobalBoolean("MAN_SHALASF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SHALASF_DONE");
    }
    if (GetGlobalBoolean("MAN_SHALASQ_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SHALASQ_DONE");
    }
    if (GetGlobalBoolean("MAN_SITHACF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SITHACF_DONE");
    }
    if (GetGlobalBoolean("MAN_REPACF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_REPACF_DONE");
    }
    if (GetGlobalBoolean("MAN_SITHF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SITHF_DONE");
    }
    if (GetGlobalBoolean("MAN_SITHB1_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SITHB1_DONE");
    }
    if (GetGlobalBoolean("MAN_SITHB2_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SITHB2_DONE");
    }
    if (GetGlobalBoolean("MAN_DOOR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_DOOR_DONE");
    }
    if (GetGlobalBoolean("MAN_OPEN_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_OPEN_DONE");
    }
    if (GetGlobalBoolean("MAN_SITHT_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SITHT_DONE");
    }
    if (GetGlobalBoolean("MAN_SUNRYJF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SUNRYJF_DONE");
    }
    if (GetGlobalBoolean("MAN_SUNRYF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SUNRYF_DONE");
    }
    if (GetGlobalBoolean("MAN_TYVARKD_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_TYVARKD_DONE");
    }
    if (GetGlobalBoolean("MAN_SECRET_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SECRET_DONE");
    }
    if (GetGlobalBoolean("MAN_CONFESS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_CONFESS_DONE");
    }
    if (GetGlobalBoolean("MAN_VIGLOF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_VIGLOF_DONE");
    }
    if (GetGlobalBoolean("MAN_YUKAF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_YUKAF_DONE");
    }
    if (GetGlobalBoolean("MAN_ZORIISF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_ZORIISF_DONE");
    }
    if (GetGlobalBoolean("MAN_REWARD_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_REWARD_DONE");
    }
    if (GetGlobalBoolean("MAN_ELORAFT_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_ELORAFT_DONE");
    }
    if (GetGlobalBoolean("MAN_REPS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_REPS_DONE");
    }
    if (GetGlobalBoolean("MAN_SITHS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SITHS_DONE");
    }
    if (GetGlobalBoolean("MAN_FIRITHI_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_FIRITHI_DONE");
    }
    if (GetGlobalBoolean("MAN_FIRITHH_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_FIRITHH_DONE");
    }
    if (GetGlobalBoolean("MAN_MERCD_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_MERCD_DONE");
    }
    if (GetGlobalBoolean("MAN_GONTOI_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_GONTOI_DONE");
    }
    if (GetGlobalBoolean("MAN_GONTOH_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_GONTOH_DONE");
    }
    if (GetGlobalBoolean("DAN_VROOKB_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VROOKB_DONE");
    }
    if (GetGlobalBoolean("DAN_NEMOB_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_NEMOB_DONE");
    }
    if (GetGlobalBoolean("DAN_VANDARM_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VANDARM_DONE");
    }
    if (GetGlobalBoolean("MAN_IRIDORS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_IRIDORS_DONE");
    }
    if (GetGlobalBoolean("MAN_KILLS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_KILLS_DONE");
    }
    if (GetGlobalBoolean("MAN_SHALASC_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SHALASC_DONE");
    }
    if (GetGlobalBoolean("MAN_AFFAIR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_AFFAIR_DONE");
    }
    if (GetGlobalBoolean("MAN_GONTOM_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_GONTOM_DONE");
    }
    if (GetGlobalBoolean("MAN_MIND_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_MIND_DONE");
    }
    if (GetGlobalBoolean("MAN_SITHFF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SITHFF_DONE");
    }
    if (GetGlobalBoolean("MAN_AUTOM_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_AUTOM_DONE");
    }
    if (GetGlobalBoolean("MAN_AUTOF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_AUTOF_DONE");
    }
    if (GetGlobalBoolean("MAN_YORTALH_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_YORTALH_DONE");
    }
    if (GetGlobalBoolean("MAN_YORTALS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_YORTALS_DONE");
    }
    if (GetGlobalBoolean("MAN_YORTALM_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_YORTALM_DONE");
    }
    if (GetGlobalBoolean("MAN_QUEEDLE_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_QUEEDLE_DONE");
    }
    if (GetGlobalBoolean("MAN_HUKTAL_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_HUKTAL_DONE");
    }
    if (GetGlobalBoolean("MAN_SWOOPR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SWOOPR_DONE");
    }
    if (GetGlobalBoolean("MAN_AUTOGM_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_AUTOGM_DONE");
    }
    if (GetGlobalBoolean("MAN_AUTOGF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_AUTOGF_DONE");
    }
    if (GetGlobalBoolean("MAN_SITHSMF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SITHSMF_DONE");
    }
    if (GetGlobalBoolean("MAN_SITHSFF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SITHSFF_DONE");
    }
    if (GetGlobalBoolean("MAN_SITHSC_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SITHSC_DONE");
    }
    if (GetGlobalBoolean("MAN_SHASAQ_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SHASAQ_DONE");
    }
    if (GetGlobalBoolean("DAN_DIARY_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_DIARY_DONE");
    }
    if (GetGlobalBoolean("DAN_LIEM_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_LIEM_DONE");
    }
    if (GetGlobalBoolean("DAN_LIED_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_LIED_DONE");
    }
    if (GetGlobalBoolean("DAN_ANGER5_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ANGER5_DONE");
    }
    if (GetGlobalBoolean("DAN_ANGER6_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ANGER6_DONE");
    }
    if (GetGlobalBoolean("DAN_ANGER7_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ANGER7_DONE");
    }
    if (GetGlobalBoolean("MAN_SITHMEF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SITHMEF_DONE");
    }
    if (GetGlobalBoolean("DAN_VANDARF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VANDARF_DONE");
    }
    if (GetGlobalBoolean("DAN_BASTM_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_BASTM_DONE");
    }
    if (GetGlobalBoolean("DAN_VANDAR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VANDAR_DONE");
    }
    if (GetGlobalBoolean("DAN_JUHANIF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_JUHANIF_DONE");
    }
    if (GetGlobalBoolean("DAN_ELISEF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ELISEF_DONE");
    }
    if (GetGlobalBoolean("MAN_SHALASH_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SHALASH_DONE");
    }
    if (GetGlobalBoolean("DAN_ELISEH_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ELISEH_DONE");
    }
    if (GetGlobalBoolean("DAN_BOLOOKF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_BOLOOKF_DONE");
    }
    if (GetGlobalBoolean("DAN_HANDONF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_HANDONF_DONE");
    }
    if (GetGlobalBoolean("DAN_RICKARDF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_RICKARDF_DONE");
    }
    if (GetGlobalBoolean("DAN_IDROIDF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_IDROIDF_DONE");
    }
    if (GetGlobalBoolean("DAN_IDROIDB_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_IDROIDB_DONE");
    }
    if (GetGlobalBoolean("T_JUHANIR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|T_JUHANIR_DONE");
    }
    if (GetGlobalBoolean("DAN_HANDONG_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_HANDONG_DONE");
    }
    if (GetGlobalBoolean("MAN_REPHACK_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_REPHACK_DONE");
    }
    if (GetGlobalBoolean("MAN_SITHPASS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SITHPASS_DONE");
    }
    if (GetGlobalBoolean("MAN_INTERR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_INTERR_DONE");
    }
    if (GetGlobalBoolean("MAN_PERS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_PERS_DONE");
    }
    if (GetGlobalBoolean("MAN_PTRAP_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_PTRAP_DONE");
    }
    if (GetGlobalBoolean("MAN_SUNAFF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SUNAFF_DONE");
    }
    if (GetGlobalBoolean("MAN_SUNAFFD_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SUNAFFD_DONE");
    }
    if (GetGlobalBoolean("MAN_ELORAS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_ELORAS_DONE");
    }
    if (GetGlobalBoolean("MAN_IGNUSL_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_IGNUSL_DONE");
    }
    if (GetGlobalBoolean("MAN_GLUUPEV_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_GLUUPEV_DONE");
    }
    if (GetGlobalBoolean("MAN_TYVARKM_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_TYVARKM_DONE");
    }
    if (GetGlobalBoolean("MAN_SWOOP_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_SWOOP_DONE");
    }
    if (GetGlobalBoolean("DAN_ZHARR_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_ZHARR_DONE");
    }
    if (GetGlobalBoolean("DAN_VROOKS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VROOKS_DONE");
    }
    if (GetGlobalBoolean("MAN_HRAKERT_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_HRAKERT_DONE");
    }
    if (GetGlobalBoolean("MAN_REPTECH1_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_REPTECH1_DONE");
    }
    if (GetGlobalBoolean("MAN_REPTECH2_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_REPTECH2_DONE");
    }
    if (GetGlobalBoolean("MAN_COMP_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_COMP_DONE");
    }
    if (GetGlobalBoolean("MAN_YORTALF_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_YORTALF_DONE");
    }
    if (GetGlobalBoolean("DAN_LIFE_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_LIFE_DONE");
    }
    if (GetGlobalBoolean("DAN_DEATH_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_DEATH_DONE");
    }
    if (GetGlobalBoolean("MAN_TYVARKS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_TYVARKS_DONE");
    }
    if (GetGlobalBoolean("MAN_TYVARKC_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_TYVARKC_DONE");
    }
    if (GetGlobalBoolean("DAN_KARALK_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_KARALK_DONE");
    }
    if (GetGlobalBoolean("DAN_KARALC_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_KARALC_DONE");
    }
    if (GetGlobalBoolean("DAN_KARALS_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_KARALS_DONE");
    }
    if (GetGlobalBoolean("DAN_CRATISC_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_CRATISC_DONE");
    }
    if (GetGlobalBoolean("DAN_CRATISK_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_CRATISK_DONE");
    }
    if (GetGlobalBoolean("MAN_YORTALK_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_YORTALK_DONE");
    }
    if (GetGlobalBoolean("MAN_YORTALC_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|MAN_YORTALC_DONE");
    }
    if (GetGlobalBoolean("DAN_VANDARB_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VANDARB_DONE");
    }
    if (GetGlobalBoolean("DAN_VROOKBB_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_VROOKBB_DONE");
    }
    if (GetGlobalBoolean("TAT_SWOOP_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|TAT_SWOOP_DONE");
    }
    if (GetGlobalBoolean("DAN_DORAK_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_DORAK_DONE");
    }
    if (GetGlobalBoolean("DAN_SABER_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_SABER_DONE");
    }
    if (GetGlobalBoolean("DEMO_FIELD_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DEMO_FIELD_DONE");
    }
    if (GetGlobalBoolean("ebo_turret_done"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|ebo_turret_done");
    }
    if (GetGlobalBoolean("DAN_SOL_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_SOL_DONE");
    }
    if (GetGlobalBoolean("UNK_SWITCH_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|UNK_SWITCH_DONE");
    }
    if (GetGlobalBoolean("DAN_TAREEJ_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|DAN_TAREEJ_DONE");
    }
    if (GetGlobalBoolean("UNK_PUZG_DONE"))
    {
        KSE_Diag(21, "AP|CHECK|QUEST|UNK_PUZG_DONE");
    }
}

// _PLOT trackers are real globalcat.2da Number globals (same proven-
// reliable category as the _DONE booleans above -- not a custom name, so
// no workaround needed). Reports the CURRENT stage value every poll,
// skipping 0 (not-yet-started, nothing for the client to act on). The
// client derives 'newly reached stage N' by comparing against its own
// memory of the highest stage already converted into a check, and can
// map each newly-crossed threshold to a separate AP location.
void CheckPlot()
{
    int nMAIN_PLOT = GetGlobalNumber("MAIN_PLOT");
    if (nMAIN_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|MAIN_PLOT|value=" + IntToString(nMAIN_PLOT));
    }
    int nDAN_PLANET_PLOT = GetGlobalNumber("DAN_PLANET_PLOT");
    if (nDAN_PLANET_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|DAN_PLANET_PLOT|value=" + IntToString(nDAN_PLANET_PLOT));
    }
    int nDAN_ROMANCE_PLOT = GetGlobalNumber("DAN_ROMANCE_PLOT");
    if (nDAN_ROMANCE_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|DAN_ROMANCE_PLOT|value=" + IntToString(nDAN_ROMANCE_PLOT));
    }
    int nDAN_JEDI_PLOT = GetGlobalNumber("DAN_JEDI_PLOT");
    if (nDAN_JEDI_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|DAN_JEDI_PLOT|value=" + IntToString(nDAN_JEDI_PLOT));
    }
    int nDAN_JUHANI_PLOT = GetGlobalNumber("DAN_JUHANI_PLOT");
    if (nDAN_JUHANI_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|DAN_JUHANI_PLOT|value=" + IntToString(nDAN_JUHANI_PLOT));
    }
    int nDAN_CASUS_PLOT = GetGlobalNumber("DAN_CASUS_PLOT");
    if (nDAN_CASUS_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|DAN_CASUS_PLOT|value=" + IntToString(nDAN_CASUS_PLOT));
    }
    int nMAN_PLANET_PLOT = GetGlobalNumber("MAN_PLANET_PLOT");
    if (nMAN_PLANET_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|MAN_PLANET_PLOT|value=" + IntToString(nMAN_PLANET_PLOT));
    }
    int nMAN_MURDER_PLOT = GetGlobalNumber("MAN_MURDER_PLOT");
    if (nMAN_MURDER_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|MAN_MURDER_PLOT|value=" + IntToString(nMAN_MURDER_PLOT));
    }
    int nMAN_RODIAN_PLOT = GetGlobalNumber("MAN_RODIAN_PLOT");
    if (nMAN_RODIAN_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|MAN_RODIAN_PLOT|value=" + IntToString(nMAN_RODIAN_PLOT));
    }
    int nMAN_MISSING_PLOT = GetGlobalNumber("MAN_MISSING_PLOT");
    if (nMAN_MISSING_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|MAN_MISSING_PLOT|value=" + IntToString(nMAN_MISSING_PLOT));
    }
    int nDAN_ELISE_PLOT = GetGlobalNumber("DAN_ELISE_PLOT");
    if (nDAN_ELISE_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|DAN_ELISE_PLOT|value=" + IntToString(nDAN_ELISE_PLOT));
    }
    int nKOR_LASHOWE_PLOT = GetGlobalNumber("KOR_LASHOWE_PLOT");
    if (nKOR_LASHOWE_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|KOR_LASHOWE_PLOT|value=" + IntToString(nKOR_LASHOWE_PLOT));
    }
    int nG_CAND_PLOT = GetGlobalNumber("G_CAND_PLOT");
    if (nG_CAND_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|G_CAND_PLOT|value=" + IntToString(nG_CAND_PLOT));
    }
    int nG_JUHANI_PLOT = GetGlobalNumber("G_JUHANI_PLOT");
    if (nG_JUHANI_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|G_JUHANI_PLOT|value=" + IntToString(nG_JUHANI_PLOT));
    }
    int nEBO_SASHA_PLOT = GetGlobalNumber("EBO_SASHA_PLOT");
    if (nEBO_SASHA_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|EBO_SASHA_PLOT|value=" + IntToString(nEBO_SASHA_PLOT));
    }
    int nEBO_GIZKA_PLOT = GetGlobalNumber("EBO_GIZKA_PLOT");
    if (nEBO_GIZKA_PLOT > 0)
    {
        KSE_Diag(25, "AP|CHECK|PLOT|EBO_GIZKA_PLOT|value=" + IntToString(nEBO_GIZKA_PLOT));
    }
}

// Game-wide quest tracking via KOTOR's own journal system -- covers all
// 9 planets (the _DONE/_PLOT globals above are Dantooine/Manaan-specific
// internal bookkeeping, not player-visible, so they aren't used as a
// location source; the journal is what the player actually sees update).
// GetJournalEntry(tag) reads the current stage for any quest, same
// reliability class as GetGlobalNumber -- a real, documented engine call,
// not a workaround. Reports nonzero stages every poll, same stateless
// pattern as CheckPlot(): the client tracks which (tag, stage) pairs it's
// already converted into a check.
void CheckJournal()
{
    int ntat18ac_dragonhunt = GetJournalEntry("tat18ac_dragonhunt");
    if (ntat18ac_dragonhunt > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tat18ac_dragonhunt|value=" + IntToString(ntat18ac_dragonhunt));
    }
    int nkor25_doubtsith = GetJournalEntry("kor25_doubtsith");
    if (nkor25_doubtsith > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kor25_doubtsith|value=" + IntToString(nkor25_doubtsith));
    }
    int nk_starforge = GetJournalEntry("k_starforge");
    if (nk_starforge > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_starforge|value=" + IntToString(nk_starforge));
    }
    int ntar_rancor = GetJournalEntry("tar_rancor");
    if (ntar_rancor > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_rancor|value=" + IntToString(ntar_rancor));
    }
    int nkas23_rorworr = GetJournalEntry("kas23_rorworr");
    if (nkas23_rorworr > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kas23_rorworr|value=" + IntToString(nkas23_rorworr));
    }
    int nkor35_aidlashowe = GetJournalEntry("kor35_aidlashowe");
    if (nkor35_aidlashowe > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kor35_aidlashowe|value=" + IntToString(nkor35_aidlashowe));
    }
    int nend_attack = GetJournalEntry("end_attack");
    if (nend_attack > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|end_attack|value=" + IntToString(nend_attack));
    }
    int nk_swg_bastilatalk = GetJournalEntry("k_swg_bastilatalk");
    if (nk_swg_bastilatalk > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_swg_bastilatalk|value=" + IntToString(nk_swg_bastilatalk));
    }
    int nk_swg_helenatalk = GetJournalEntry("k_swg_helenatalk");
    if (nk_swg_helenatalk > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_swg_helenatalk|value=" + IntToString(nk_swg_helenatalk));
    }
    int ntar_bendakbounty = GetJournalEntry("tar_bendakbounty");
    if (ntar_bendakbounty > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_bendakbounty|value=" + IntToString(ntar_bendakbounty));
    }
    int nk_swg_canderous = GetJournalEntry("k_swg_canderous");
    if (nk_swg_canderous > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_swg_canderous|value=" + IntToString(nk_swg_canderous));
    }
    int nlev_captured = GetJournalEntry("lev_captured");
    if (nlev_captured > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|lev_captured|value=" + IntToString(nlev_captured));
    }
    int nk_swg_carthtalk = GetJournalEntry("k_swg_carthtalk");
    if (nk_swg_carthtalk > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_swg_carthtalk|value=" + IntToString(nk_swg_carthtalk));
    }
    int nkas23_mainwookplot = GetJournalEntry("kas23_mainwookplot");
    if (nkas23_mainwookplot > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kas23_mainwookplot|value=" + IntToString(nkas23_mainwookplot));
    }
    int ndan_casus = GetJournalEntry("dan_casus");
    if (ndan_casus > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|dan_casus|value=" + IntToString(ndan_casus));
    }
    int ntat_ambush = GetJournalEntry("tat_ambush");
    if (ntat_ambush > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tat_ambush|value=" + IntToString(ntat_ambush));
    }
    int ntar_diabounty = GetJournalEntry("tar_diabounty");
    if (ntar_diabounty > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_diabounty|value=" + IntToString(ntar_diabounty));
    }
    int ntat17ad_buyinghk47 = GetJournalEntry("tat17ad_buyinghk47");
    if (ntat17ad_buyinghk47 > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tat17ad_buyinghk47|value=" + IntToString(ntat17ad_buyinghk47));
    }
    int nebo_supplies = GetJournalEntry("ebo_supplies");
    if (nebo_supplies > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|ebo_supplies|value=" + IntToString(nebo_supplies));
    }
    int nman_elora = GetJournalEntry("man_elora");
    if (nman_elora > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|man_elora|value=" + IntToString(nman_elora));
    }
    int nkor33_enteracademy = GetJournalEntry("kor33_enteracademy");
    if (nkor33_enteracademy > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kor33_enteracademy|value=" + IntToString(nkor33_enteracademy));
    }
    int ntar_escape = GetJournalEntry("tar_escape");
    if (ntar_escape > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_escape|value=" + IntToString(ntar_escape));
    }
    int ntat17aa_jawarescue = GetJournalEntry("tat17aa_jawarescue");
    if (ntat17aa_jawarescue > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tat17aa_jawarescue|value=" + IntToString(ntat17aa_jawarescue));
    }
    int nkor35_findingdustil = GetJournalEntry("kor35_findingdustil");
    if (nkor35_findingdustil > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kor35_findingdustil|value=" + IntToString(nkor35_findingdustil));
    }
    int nman_firith = GetJournalEntry("man_firith");
    if (nman_firith > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|man_firith|value=" + IntToString(nman_firith));
    }
    int nGenoharadan = GetJournalEntry("Genoharadan");
    if (nGenoharadan > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|Genoharadan|value=" + IntToString(nGenoharadan));
    }
    int nGeno_Ithorak = GetJournalEntry("Geno_Ithorak");
    if (nGeno_Ithorak > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|Geno_Ithorak|value=" + IntToString(nGeno_Ithorak));
    }
    int nGeno_Lorgal = GetJournalEntry("Geno_Lorgal");
    if (nGeno_Lorgal > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|Geno_Lorgal|value=" + IntToString(nGeno_Lorgal));
    }
    int nGeno_Rulan = GetJournalEntry("Geno_Rulan");
    if (nGeno_Rulan > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|Geno_Rulan|value=" + IntToString(nGeno_Rulan));
    }
    int nGeno_Vorn = GetJournalEntry("Geno_Vorn");
    if (nGeno_Vorn > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|Geno_Vorn|value=" + IntToString(nGeno_Vorn));
    }
    int nGeno_Zuulan = GetJournalEntry("Geno_Zuulan");
    if (nGeno_Zuulan > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|Geno_Zuulan|value=" + IntToString(nGeno_Zuulan));
    }
    int nman_gluupor = GetJournalEntry("man_gluupor");
    if (nman_gluupor > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|man_gluupor|value=" + IntToString(nman_gluupor));
    }
    int nkas25_mandalorians = GetJournalEntry("kas25_mandalorians");
    if (nkas25_mandalorians > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kas25_mandalorians|value=" + IntToString(nkas25_mandalorians));
    }
    int nk_swg_hk47talk = GetJournalEntry("k_swg_hk47talk");
    if (nk_swg_hk47talk > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_swg_hk47talk|value=" + IntToString(nk_swg_hk47talk));
    }
    int nkas22_EliMatton = GetJournalEntry("kas22_EliMatton");
    if (nkas22_EliMatton > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kas22_EliMatton|value=" + IntToString(nkas22_EliMatton));
    }
    int nman_ignus = GetJournalEntry("man_ignus");
    if (nman_ignus > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|man_ignus|value=" + IntToString(nman_ignus));
    }
    int ntar_infectedoutcasts = GetJournalEntry("tar_infectedoutcasts");
    if (ntar_infectedoutcasts > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_infectedoutcasts|value=" + IntToString(ntar_infectedoutcasts));
    }
    int ntar_vulkarbase = GetJournalEntry("tar_vulkarbase");
    if (ntar_vulkarbase > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_vulkarbase|value=" + IntToString(ntar_vulkarbase));
    }
    int ndan_ruins = GetJournalEntry("dan_ruins");
    if (ndan_ruins > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|dan_ruins|value=" + IntToString(ndan_ruins));
    }
    int nunk_invis = GetJournalEntry("unk_invis");
    if (nunk_invis > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|unk_invis|value=" + IntToString(nunk_invis));
    }
    int ntar_party = GetJournalEntry("tar_party");
    if (ntar_party > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_party|value=" + IntToString(ntar_party));
    }
    int nk_jagi = GetJournalEntry("k_jagi");
    if (nk_jagi > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_jagi|value=" + IntToString(nk_jagi));
    }
    int ndan_trials = GetJournalEntry("dan_trials");
    if (ndan_trials > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|dan_trials|value=" + IntToString(ndan_trials));
    }
    int nk_swg_joleetalk = GetJournalEntry("k_swg_joleetalk");
    if (nk_swg_joleetalk > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_swg_joleetalk|value=" + IntToString(nk_swg_joleetalk));
    }
    int nkas24_removepoachers = GetJournalEntry("kas24_removepoachers");
    if (nkas24_removepoachers > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kas24_removepoachers|value=" + IntToString(nkas24_removepoachers));
    }
    int nk_swg_juhani = GetJournalEntry("k_swg_juhani");
    if (nk_swg_juhani > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_swg_juhani|value=" + IntToString(nk_swg_juhani));
    }
    int ntar_largobounty = GetJournalEntry("tar_largobounty");
    if (ntar_largobounty > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_largobounty|value=" + IntToString(ntar_largobounty));
    }
    int nMan26ab_swoopraces = GetJournalEntry("Man26ab_swoopraces");
    if (nMan26ab_swoopraces > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|Man26ab_swoopraces|value=" + IntToString(nMan26ab_swoopraces));
    }
    int ndan_raiders = GetJournalEntry("dan_raiders");
    if (ndan_raiders > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|dan_raiders|value=" + IntToString(ndan_raiders));
    }
    int ntar_matrik = GetJournalEntry("tar_matrik");
    if (ntar_matrik > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_matrik|value=" + IntToString(ntar_matrik));
    }
    int ntar_meetCand = GetJournalEntry("tar_meetCand");
    if (ntar_meetCand > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_meetCand|value=" + IntToString(ntar_meetCand));
    }
    int ntat17aa_middleman = GetJournalEntry("tat17aa_middleman");
    if (ntat17aa_middleman > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tat17aa_middleman|value=" + IntToString(ntat17aa_middleman));
    }
    int ndan_companion = GetJournalEntry("dan_companion");
    if (ndan_companion > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|dan_companion|value=" + IntToString(ndan_companion));
    }
    int nman_missing = GetJournalEntry("man_missing");
    if (nman_missing > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|man_missing|value=" + IntToString(nman_missing));
    }
    int nman_planet = GetJournalEntry("man_planet");
    if (nman_planet > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|man_planet|value=" + IntToString(nman_planet));
    }
    int nk_missbroth = GetJournalEntry("k_missbroth");
    if (nk_missbroth > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_missbroth|value=" + IntToString(nk_missbroth));
    }
    int ndan_murder = GetJournalEntry("dan_murder");
    if (ndan_murder > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|dan_murder|value=" + IntToString(ndan_murder));
    }
    int nk_pazaak = GetJournalEntry("k_pazaak");
    if (nk_pazaak > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_pazaak|value=" + IntToString(nk_pazaak));
    }
    int nmain_premium = GetJournalEntry("main_premium");
    if (nmain_premium > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|main_premium|value=" + IntToString(nmain_premium));
    }
    int ntar_buydroid = GetJournalEntry("tar_buydroid");
    if (ntar_buydroid > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_buydroid|value=" + IntToString(ntar_buydroid));
    }
    int nunk_research = GetJournalEntry("unk_research");
    if (nunk_research > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|unk_research|value=" + IntToString(nunk_research));
    }
    int ntar_rakghoulserum = GetJournalEntry("tar_rakghoulserum");
    if (ntar_rakghoulserum > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_rakghoulserum|value=" + IntToString(ntar_rakghoulserum));
    }
    int nk_rapidtransit = GetJournalEntry("k_rapidtransit");
    if (nk_rapidtransit > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_rapidtransit|value=" + IntToString(nk_rapidtransit));
    }
    int nkor35_renegadesith = GetJournalEntry("kor35_renegadesith");
    if (nkor35_renegadesith > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kor35_renegadesith|value=" + IntToString(nkor35_renegadesith));
    }
    int nman_emb = GetJournalEntry("man_emb");
    if (nman_emb > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|man_emb|value=" + IntToString(nman_emb));
    }
    int nman_merc = GetJournalEntry("man_merc");
    if (nman_merc > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|man_merc|value=" + IntToString(nman_merc));
    }
    int nkor38_roguedroid = GetJournalEntry("kor38_roguedroid");
    if (nkor38_roguedroid > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kor38_roguedroid|value=" + IntToString(nkor38_roguedroid));
    }
    int ntar_rukilapprentice = GetJournalEntry("tar_rukilapprentice");
    if (ntar_rukilapprentice > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_rukilapprentice|value=" + IntToString(ntar_rukilapprentice));
    }
    int ntat17ag_sandbounty = GetJournalEntry("tat17ag_sandbounty");
    if (ntat17ag_sandbounty > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tat17ag_sandbounty|value=" + IntToString(ntat17ag_sandbounty));
    }
    int ndan_romance = GetJournalEntry("dan_romance");
    if (ndan_romance > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|dan_romance|value=" + IntToString(ndan_romance));
    }
    int ntar_selvenbounty = GetJournalEntry("tar_selvenbounty");
    if (ntar_selvenbounty > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_selvenbounty|value=" + IntToString(ntar_selvenbounty));
    }
    int ntat17ae_signingnico = GetJournalEntry("tat17ae_signingnico");
    if (ntat17ae_signingnico > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tat17ae_signingnico|value=" + IntToString(ntat17ae_signingnico));
    }
    int nkas22_starmap = GetJournalEntry("kas22_starmap");
    if (nkas22_starmap > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kas22_starmap|value=" + IntToString(nkas22_starmap));
    }
    int nkor33_findstarmap = GetJournalEntry("kor33_findstarmap");
    if (nkor33_findstarmap > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kor33_findstarmap|value=" + IntToString(nkor33_findstarmap));
    }
    int nman26_starmap = GetJournalEntry("man26_starmap");
    if (nman26_starmap > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|man26_starmap|value=" + IntToString(nman26_starmap));
    }
    int ntat17_starmap = GetJournalEntry("tat17_starmap");
    if (ntat17_starmap > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tat17_starmap|value=" + IntToString(ntat17_starmap));
    }
    int nk_pebo_stowaway = GetJournalEntry("k_pebo_stowaway");
    if (nk_pebo_stowaway > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_pebo_stowaway|value=" + IntToString(nk_pebo_stowaway));
    }
    int nman_murder = GetJournalEntry("man_murder");
    if (nman_murder > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|man_murder|value=" + IntToString(nman_murder));
    }
    int nman_sunry = GetJournalEntry("man_sunry");
    if (nman_sunry > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|man_sunry|value=" + IntToString(nman_sunry));
    }
    int nkas24_tachpoaching = GetJournalEntry("kas24_tachpoaching");
    if (nkas24_tachpoaching > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kas24_tachpoaching|value=" + IntToString(nkas24_tachpoaching));
    }
    int ntat18aa_tanistrapped = GetJournalEntry("tat18aa_tanistrapped");
    if (ntat18aa_tanistrapped > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tat18aa_tanistrapped|value=" + IntToString(ntat18aa_tanistrapped));
    }
    int ntar_planetinfo = GetJournalEntry("tar_planetinfo");
    if (ntar_planetinfo > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_planetinfo|value=" + IntToString(ntar_planetinfo));
    }
    int ntat17ae_swoopracing = GetJournalEntry("tat17ae_swoopracing");
    if (ntat17ae_swoopracing > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tat17ae_swoopracing|value=" + IntToString(ntat17ae_swoopracing));
    }
    int nCategory000 = GetJournalEntry("Category000");
    if (nCategory000 > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|Category000|value=" + IntToString(nCategory000));
    }
    int nkor35_doublecross = GetJournalEntry("kor35_doublecross");
    if (nkor35_doublecross > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kor35_doublecross|value=" + IntToString(nkor35_doublecross));
    }
    int nkor35_doublecross2 = GetJournalEntry("kor35_doublecross2");
    if (nkor35_doublecross2 > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kor35_doublecross2|value=" + IntToString(nkor35_doublecross2));
    }
    int ntar_duelring = GetJournalEntry("tar_duelring");
    if (ntar_duelring > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_duelring|value=" + IntToString(ntar_duelring));
    }
    int nk_ebonhawk = GetJournalEntry("k_ebonhawk");
    if (nk_ebonhawk > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_ebonhawk|value=" + IntToString(nk_ebonhawk));
    }
    int nsta_confront = GetJournalEntry("sta_confront");
    if (nsta_confront > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|sta_confront|value=" + IntToString(nsta_confront));
    }
    int nkor38_hermit = GetJournalEntry("kor38_hermit");
    if (nkor38_hermit > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kor38_hermit|value=" + IntToString(nkor38_hermit));
    }
    int ndan_council = GetJournalEntry("dan_council");
    if (ndan_council > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|dan_council|value=" + IntToString(ndan_council));
    }
    int nkor35_mandalorian = GetJournalEntry("kor35_mandalorian");
    if (nkor35_mandalorian > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kor35_mandalorian|value=" + IntToString(nkor35_mandalorian));
    }
    int ntar_promisedland = GetJournalEntry("tar_promisedland");
    if (ntar_promisedland > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_promisedland|value=" + IntToString(ntar_promisedland));
    }
    int ntar_bastsearch = GetJournalEntry("tar_bastsearch");
    if (ntar_bastsearch > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|tar_bastsearch|value=" + IntToString(ntar_bastsearch));
    }
    int nkor37_ajuntapall = GetJournalEntry("kor37_ajuntapall");
    if (nkor37_ajuntapall > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kor37_ajuntapall|value=" + IntToString(nkor37_ajuntapall));
    }
    int nk_pebo_gizkatrouble = GetJournalEntry("k_pebo_gizkatrouble");
    if (nk_pebo_gizkatrouble > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_pebo_gizkatrouble|value=" + IntToString(nk_pebo_gizkatrouble));
    }
    int nkor35_waysith = GetJournalEntry("kor35_waysith");
    if (nkor35_waysith > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|kor35_waysith|value=" + IntToString(nkor35_waysith));
    }
    int nk_xor = GetJournalEntry("k_xor");
    if (nk_xor > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|k_xor|value=" + IntToString(nk_xor));
    }
    int nunk_trapped = GetJournalEntry("unk_trapped");
    if (nunk_trapped > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|unk_trapped|value=" + IntToString(nunk_trapped));
    }
    int nebo46_unfinishedbusiness = GetJournalEntry("ebo46_unfinishedbusiness");
    if (nebo46_unfinishedbusiness > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|ebo46_unfinishedbusiness|value=" + IntToString(nebo46_unfinishedbusiness));
    }
    int nTat20aa_worthy = GetJournalEntry("Tat20aa_worthy");
    if (nTat20aa_worthy > 0)
    {
        KSE_Diag(30, "AP|CHECK|JOURNAL|Tat20aa_worthy|value=" + IntToString(nTat20aa_worthy));
    }
}


// XP handling has moved off the old in-game revert-on-detect design
// entirely: the game no longer decides what XP is 'legitimate'. It just
// honestly reports current XP every poll -- the AP client is authoritative
// on what XP the player SHOULD have (sum of AP-granted XP items so far)
// and sends back a SetXP correction through the existing apply pipeline
// when the reported value doesn't match. No in-game persistence needed.
void CheckXP()
{
    object oPC = GetFirstPC();
    KSE_Diag(24, "AP|XPREPORT|current=" + IntToString(GetXP(oPC)));
}

// Same stateless model as XP -- credits picked up from loot/kills need the
// same suppression treatment as items, not just the explicit "credits" AP
// grant item. The STOREOPENED markers already snapshot credits at the start
// of a purchase; this is the continuous every-poll report the client needs
// to know the current total at all, same role CheckXP plays for XP.
void CheckCredits()
{
    object oPC = GetFirstPC();
    KSE_Diag(29, "AP|CREDITSREPORT|current=" + IntToString(GetGold(oPC)));
}

// Same stateless design again: ability scores are granted as PERMANENT
// effects (EffectAbilityIncrease + DURATION_TYPE_PERMANENT), which are
// tied to the specific character save they were applied to -- a brand
// new save (or a restarted playthrough) starts with none of them, same
// as vanilla. Reporting current scores every poll lets the client notice
// a fresh save is behind what's actually been earned and reapply the
// missing effects automatically, instead of the player losing progress.
void CheckAbilityScores()
{
    object oPC = GetFirstPC();
    string sReport = "AP|ABILITYREPORT|str=" + IntToString(GetAbilityScore(oPC, ABILITY_STRENGTH))
        + "|dex=" + IntToString(GetAbilityScore(oPC, ABILITY_DEXTERITY))
        + "|con=" + IntToString(GetAbilityScore(oPC, ABILITY_CONSTITUTION))
        + "|int=" + IntToString(GetAbilityScore(oPC, ABILITY_INTELLIGENCE))
        + "|wis=" + IntToString(GetAbilityScore(oPC, ABILITY_WISDOM))
        + "|cha=" + IntToString(GetAbilityScore(oPC, ABILITY_CHARISMA));
    KSE_Diag(27, sReport);
}

// Reports current Jedi class levels every poll so the client can check
// 'does this character already have class X' BEFORE sending a class-switch
// grant, not just trust its own delivery bookkeeping. AddMultiClass +
// ShowLevelUpGUI are one-shot, not safe to re-fire (confirmed: re-applying
// class_sentinel on an already-multiclassed character as part of a reconnect
// resend crashed the game). Bookkeeping alone can't be trusted across saves
// (an older save reloaded later may genuinely still need the grant), so this
// reads real game state instead -- self-correcting regardless of which save
// is currently loaded.
void CheckClasses()
{
    object oPC = GetFirstPC();
    string sReport = "AP|CLASSREPORT|guardian=" + IntToString(GetLevelByClass(CLASS_TYPE_JEDIGUARDIAN, oPC))
        + "|consular=" + IntToString(GetLevelByClass(CLASS_TYPE_JEDICONSULAR, oPC))
        + "|sentinel=" + IntToString(GetLevelByClass(CLASS_TYPE_JEDISENTINEL, oPC));
    int nBaseClass = GetClassByPosition(1, oPC);
    int nBaseLevel = GetLevelByPosition(1, oPC);
    sReport = sReport + "|baseclass=" + IntToString(nBaseClass) + "|baselevel=" + IntToString(nBaseLevel);
    KSE_Diag(65, sReport);
}

// Traps feature (2026-09-08) -- reports every feat.2da id the character
// currently holds (KSE_GetFeatAcquired is per-id membership only, there's
// no 'list all feats' native), so the client can pick half at random for
// the Remove Half Known Feats trap without guessing at what's held.
void CheckFeats()
{
    object oPC = GetFirstPC();
    string sHeld = "";
    if (KSE_GetFeatAcquired(1, oPC)) sHeld += "1,";
    if (KSE_GetFeatAcquired(2, oPC)) sHeld += "2,";
    if (KSE_GetFeatAcquired(3, oPC)) sHeld += "3,";
    if (KSE_GetFeatAcquired(4, oPC)) sHeld += "4,";
    if (KSE_GetFeatAcquired(5, oPC)) sHeld += "5,";
    if (KSE_GetFeatAcquired(6, oPC)) sHeld += "6,";
    if (KSE_GetFeatAcquired(7, oPC)) sHeld += "7,";
    if (KSE_GetFeatAcquired(8, oPC)) sHeld += "8,";
    if (KSE_GetFeatAcquired(9, oPC)) sHeld += "9,";
    if (KSE_GetFeatAcquired(10, oPC)) sHeld += "10,";
    if (KSE_GetFeatAcquired(11, oPC)) sHeld += "11,";
    if (KSE_GetFeatAcquired(12, oPC)) sHeld += "12,";
    if (KSE_GetFeatAcquired(13, oPC)) sHeld += "13,";
    if (KSE_GetFeatAcquired(14, oPC)) sHeld += "14,";
    if (KSE_GetFeatAcquired(15, oPC)) sHeld += "15,";
    if (KSE_GetFeatAcquired(16, oPC)) sHeld += "16,";
    if (KSE_GetFeatAcquired(17, oPC)) sHeld += "17,";
    if (KSE_GetFeatAcquired(18, oPC)) sHeld += "18,";
    if (KSE_GetFeatAcquired(19, oPC)) sHeld += "19,";
    if (KSE_GetFeatAcquired(20, oPC)) sHeld += "20,";
    if (KSE_GetFeatAcquired(21, oPC)) sHeld += "21,";
    if (KSE_GetFeatAcquired(22, oPC)) sHeld += "22,";
    if (KSE_GetFeatAcquired(24, oPC)) sHeld += "24,";
    if (KSE_GetFeatAcquired(25, oPC)) sHeld += "25,";
    if (KSE_GetFeatAcquired(26, oPC)) sHeld += "26,";
    if (KSE_GetFeatAcquired(27, oPC)) sHeld += "27,";
    if (KSE_GetFeatAcquired(28, oPC)) sHeld += "28,";
    if (KSE_GetFeatAcquired(29, oPC)) sHeld += "29,";
    if (KSE_GetFeatAcquired(30, oPC)) sHeld += "30,";
    if (KSE_GetFeatAcquired(31, oPC)) sHeld += "31,";
    if (KSE_GetFeatAcquired(32, oPC)) sHeld += "32,";
    if (KSE_GetFeatAcquired(33, oPC)) sHeld += "33,";
    if (KSE_GetFeatAcquired(34, oPC)) sHeld += "34,";
    if (KSE_GetFeatAcquired(35, oPC)) sHeld += "35,";
    if (KSE_GetFeatAcquired(36, oPC)) sHeld += "36,";
    if (KSE_GetFeatAcquired(37, oPC)) sHeld += "37,";
    if (KSE_GetFeatAcquired(38, oPC)) sHeld += "38,";
    if (KSE_GetFeatAcquired(39, oPC)) sHeld += "39,";
    if (KSE_GetFeatAcquired(40, oPC)) sHeld += "40,";
    if (KSE_GetFeatAcquired(41, oPC)) sHeld += "41,";
    if (KSE_GetFeatAcquired(42, oPC)) sHeld += "42,";
    if (KSE_GetFeatAcquired(43, oPC)) sHeld += "43,";
    if (KSE_GetFeatAcquired(44, oPC)) sHeld += "44,";
    if (KSE_GetFeatAcquired(45, oPC)) sHeld += "45,";
    if (KSE_GetFeatAcquired(46, oPC)) sHeld += "46,";
    if (KSE_GetFeatAcquired(47, oPC)) sHeld += "47,";
    if (KSE_GetFeatAcquired(48, oPC)) sHeld += "48,";
    if (KSE_GetFeatAcquired(49, oPC)) sHeld += "49,";
    if (KSE_GetFeatAcquired(50, oPC)) sHeld += "50,";
    if (KSE_GetFeatAcquired(51, oPC)) sHeld += "51,";
    if (KSE_GetFeatAcquired(52, oPC)) sHeld += "52,";
    if (KSE_GetFeatAcquired(53, oPC)) sHeld += "53,";
    if (KSE_GetFeatAcquired(54, oPC)) sHeld += "54,";
    if (KSE_GetFeatAcquired(55, oPC)) sHeld += "55,";
    if (KSE_GetFeatAcquired(56, oPC)) sHeld += "56,";
    if (KSE_GetFeatAcquired(57, oPC)) sHeld += "57,";
    if (KSE_GetFeatAcquired(58, oPC)) sHeld += "58,";
    if (KSE_GetFeatAcquired(60, oPC)) sHeld += "60,";
    if (KSE_GetFeatAcquired(61, oPC)) sHeld += "61,";
    if (KSE_GetFeatAcquired(62, oPC)) sHeld += "62,";
    if (KSE_GetFeatAcquired(63, oPC)) sHeld += "63,";
    if (KSE_GetFeatAcquired(64, oPC)) sHeld += "64,";
    if (KSE_GetFeatAcquired(65, oPC)) sHeld += "65,";
    if (KSE_GetFeatAcquired(66, oPC)) sHeld += "66,";
    if (KSE_GetFeatAcquired(67, oPC)) sHeld += "67,";
    if (KSE_GetFeatAcquired(68, oPC)) sHeld += "68,";
    if (KSE_GetFeatAcquired(69, oPC)) sHeld += "69,";
    if (KSE_GetFeatAcquired(70, oPC)) sHeld += "70,";
    if (KSE_GetFeatAcquired(71, oPC)) sHeld += "71,";
    if (KSE_GetFeatAcquired(72, oPC)) sHeld += "72,";
    if (KSE_GetFeatAcquired(73, oPC)) sHeld += "73,";
    if (KSE_GetFeatAcquired(74, oPC)) sHeld += "74,";
    if (KSE_GetFeatAcquired(75, oPC)) sHeld += "75,";
    if (KSE_GetFeatAcquired(76, oPC)) sHeld += "76,";
    if (KSE_GetFeatAcquired(77, oPC)) sHeld += "77,";
    if (KSE_GetFeatAcquired(78, oPC)) sHeld += "78,";
    if (KSE_GetFeatAcquired(79, oPC)) sHeld += "79,";
    if (KSE_GetFeatAcquired(80, oPC)) sHeld += "80,";
    if (KSE_GetFeatAcquired(81, oPC)) sHeld += "81,";
    if (KSE_GetFeatAcquired(82, oPC)) sHeld += "82,";
    if (KSE_GetFeatAcquired(83, oPC)) sHeld += "83,";
    if (KSE_GetFeatAcquired(84, oPC)) sHeld += "84,";
    if (KSE_GetFeatAcquired(85, oPC)) sHeld += "85,";
    if (KSE_GetFeatAcquired(86, oPC)) sHeld += "86,";
    if (KSE_GetFeatAcquired(87, oPC)) sHeld += "87,";
    if (KSE_GetFeatAcquired(88, oPC)) sHeld += "88,";
    if (KSE_GetFeatAcquired(89, oPC)) sHeld += "89,";
    if (KSE_GetFeatAcquired(90, oPC)) sHeld += "90,";
    if (KSE_GetFeatAcquired(91, oPC)) sHeld += "91,";
    if (KSE_GetFeatAcquired(92, oPC)) sHeld += "92,";
    if (KSE_GetFeatAcquired(93, oPC)) sHeld += "93,";
    if (KSE_GetFeatAcquired(94, oPC)) sHeld += "94,";
    if (KSE_GetFeatAcquired(95, oPC)) sHeld += "95,";
    if (KSE_GetFeatAcquired(96, oPC)) sHeld += "96,";
    if (KSE_GetFeatAcquired(97, oPC)) sHeld += "97,";
    if (KSE_GetFeatAcquired(98, oPC)) sHeld += "98,";
    if (KSE_GetFeatAcquired(99, oPC)) sHeld += "99,";
    if (KSE_GetFeatAcquired(100, oPC)) sHeld += "100,";
    if (KSE_GetFeatAcquired(101, oPC)) sHeld += "101,";
    if (KSE_GetFeatAcquired(102, oPC)) sHeld += "102,";
    if (KSE_GetFeatAcquired(103, oPC)) sHeld += "103,";
    if (KSE_GetFeatAcquired(104, oPC)) sHeld += "104,";
    if (KSE_GetFeatAcquired(105, oPC)) sHeld += "105,";
    if (KSE_GetFeatAcquired(106, oPC)) sHeld += "106,";
    if (KSE_GetFeatAcquired(107, oPC)) sHeld += "107,";
    if (KSE_GetFeatAcquired(108, oPC)) sHeld += "108,";
    if (KSE_GetFeatAcquired(109, oPC)) sHeld += "109,";
    if (KSE_GetFeatAcquired(110, oPC)) sHeld += "110,";
    if (KSE_GetFeatAcquired(111, oPC)) sHeld += "111,";
    if (KSE_GetFeatAcquired(112, oPC)) sHeld += "112,";
    if (KSE_GetFeatAcquired(113, oPC)) sHeld += "113,";
    if (KSE_GetFeatAcquired(114, oPC)) sHeld += "114,";
    if (KSE_GetFeatAcquired(115, oPC)) sHeld += "115,";
    if (KSE_GetFeatAcquired(116, oPC)) sHeld += "116,";
    if (KSE_GetFeatAcquired(117, oPC)) sHeld += "117,";
    if (KSE_GetFeatAcquired(118, oPC)) sHeld += "118,";
    if (KSE_GetFeatAcquired(119, oPC)) sHeld += "119,";
    if (KSE_GetFeatAcquired(120, oPC)) sHeld += "120,";
    if (KSE_GetFeatAcquired(121, oPC)) sHeld += "121,";
    if (KSE_GetFeatAcquired(122, oPC)) sHeld += "122,";
    if (KSE_GetFeatAcquired(123, oPC)) sHeld += "123,";
    if (KSE_GetFeatAcquired(124, oPC)) sHeld += "124,";
    KSE_Diag(135, "AP|FEATREPORT|" + sHeld);
}

// Same shape as CheckFeats() above, for spells.2da (force powers) --
// GetHasSpell is likewise per-id membership only.
void CheckForcePowers()
{
    object oPC = GetFirstPC();
    string sHeld = "";
    if (GetHasSpell(4, oPC)) sHeld += "4,";
    if (GetHasSpell(6, oPC)) sHeld += "6,";
    if (GetHasSpell(7, oPC)) sHeld += "7,";
    if (GetHasSpell(8, oPC)) sHeld += "8,";
    if (GetHasSpell(9, oPC)) sHeld += "9,";
    if (GetHasSpell(10, oPC)) sHeld += "10,";
    if (GetHasSpell(11, oPC)) sHeld += "11,";
    if (GetHasSpell(12, oPC)) sHeld += "12,";
    if (GetHasSpell(13, oPC)) sHeld += "13,";
    if (GetHasSpell(14, oPC)) sHeld += "14,";
    if (GetHasSpell(15, oPC)) sHeld += "15,";
    if (GetHasSpell(16, oPC)) sHeld += "16,";
    if (GetHasSpell(17, oPC)) sHeld += "17,";
    if (GetHasSpell(18, oPC)) sHeld += "18,";
    if (GetHasSpell(19, oPC)) sHeld += "19,";
    if (GetHasSpell(20, oPC)) sHeld += "20,";
    if (GetHasSpell(22, oPC)) sHeld += "22,";
    if (GetHasSpell(23, oPC)) sHeld += "23,";
    if (GetHasSpell(24, oPC)) sHeld += "24,";
    if (GetHasSpell(25, oPC)) sHeld += "25,";
    if (GetHasSpell(26, oPC)) sHeld += "26,";
    if (GetHasSpell(27, oPC)) sHeld += "27,";
    if (GetHasSpell(28, oPC)) sHeld += "28,";
    if (GetHasSpell(29, oPC)) sHeld += "29,";
    if (GetHasSpell(30, oPC)) sHeld += "30,";
    if (GetHasSpell(31, oPC)) sHeld += "31,";
    if (GetHasSpell(32, oPC)) sHeld += "32,";
    if (GetHasSpell(33, oPC)) sHeld += "33,";
    if (GetHasSpell(34, oPC)) sHeld += "34,";
    if (GetHasSpell(35, oPC)) sHeld += "35,";
    if (GetHasSpell(36, oPC)) sHeld += "36,";
    if (GetHasSpell(37, oPC)) sHeld += "37,";
    if (GetHasSpell(38, oPC)) sHeld += "38,";
    if (GetHasSpell(40, oPC)) sHeld += "40,";
    if (GetHasSpell(41, oPC)) sHeld += "41,";
    if (GetHasSpell(42, oPC)) sHeld += "42,";
    if (GetHasSpell(43, oPC)) sHeld += "43,";
    if (GetHasSpell(44, oPC)) sHeld += "44,";
    if (GetHasSpell(45, oPC)) sHeld += "45,";
    if (GetHasSpell(46, oPC)) sHeld += "46,";
    if (GetHasSpell(47, oPC)) sHeld += "47,";
    if (GetHasSpell(48, oPC)) sHeld += "48,";
    if (GetHasSpell(49, oPC)) sHeld += "49,";
    if (GetHasSpell(50, oPC)) sHeld += "50,";
    KSE_Diag(136, "AP|POWERREPORT|" + sHeld);
}

// Character name, reported every poll -- the client keys its persistent
// delivery log on (character name, item index) so a fresh character (a
// deliberate restart) gets everything re-granted, while reconnecting to the
// SAME character doesn't replay history it's already received. See
// KotorClient.py's delivery log for the other half of this.
void CheckCharacterName()
{
    object oPC = GetFirstPC();
    KSE_Diag(66, "AP|NAMEREPORT|" + GetName(oPC));
}

// Same stateless design as everything above. Skills are already grantable
// via KSE_AdjustCreatureSkills (proven working in an earlier phase) -- this
// is just the reporting half, so the client can be authoritative on what
// skill ranks the player should have (same as XP/credits/inventory) rather
// than the game deciding anything for itself.
void CheckSkills()
{
    object oPC = GetFirstPC();
    string sReport = "AP|SKILLREPORT|computeruse=" + IntToString(GetSkillRank(SKILL_COMPUTER_USE, oPC))
        + "|demolitions=" + IntToString(GetSkillRank(SKILL_DEMOLITIONS, oPC))
        + "|stealth=" + IntToString(GetSkillRank(SKILL_STEALTH, oPC))
        + "|awareness=" + IntToString(GetSkillRank(SKILL_AWARENESS, oPC))
        + "|persuade=" + IntToString(GetSkillRank(SKILL_PERSUADE, oPC))
        + "|repair=" + IntToString(GetSkillRank(SKILL_REPAIR, oPC))
        + "|security=" + IntToString(GetSkillRank(SKILL_SECURITY, oPC))
        + "|treatinjury=" + IntToString(GetSkillRank(SKILL_TREAT_INJURY, oPC));
    KSE_Diag(28, sReport);
}

// Same stateless design as CheckXP() -- the game doesn't decide what's
// legitimate, it just honestly reports current inventory (backpack +
// equipped slots) every poll. The AP client correlates this against its
// own memory (starting kit, AP grants, and STOREOPENED snapshots from
// ap_store suppressors) to decide what should be removed. Backpack items
// use GetFirstItemInInventory/GetNextItemInInventory; GetFirstItemInInventory
// does NOT include equipped gear, so equipped slots are checked separately.
void CheckInventory()
{
    object oPC = GetFirstPC();
    string sReport = "AP|INVENTORY|";

    object oItem = GetFirstItemInInventory(oPC);
    while (GetIsObjectValid(oItem))
    {
        sReport = sReport + GetTag(oItem) + ":" + IntToString(GetItemStackSize(oItem)) + ",";
        oItem = GetNextItemInInventory(oPC);
    }

    object oEq;
    oEq = GetItemInSlot(INVENTORY_SLOT_HEAD, oPC);
    if (GetIsObjectValid(oEq))
    {
        sReport = sReport + "EQ_HEAD:" + GetTag(oEq) + ",";
    }
    oEq = GetItemInSlot(INVENTORY_SLOT_BODY, oPC);
    if (GetIsObjectValid(oEq))
    {
        sReport = sReport + "EQ_BODY:" + GetTag(oEq) + ",";
    }
    oEq = GetItemInSlot(INVENTORY_SLOT_HANDS, oPC);
    if (GetIsObjectValid(oEq))
    {
        sReport = sReport + "EQ_HANDS:" + GetTag(oEq) + ",";
    }
    oEq = GetItemInSlot(INVENTORY_SLOT_RIGHTWEAPON, oPC);
    if (GetIsObjectValid(oEq))
    {
        sReport = sReport + "EQ_RWEAPON:" + GetTag(oEq) + ",";
    }
    oEq = GetItemInSlot(INVENTORY_SLOT_LEFTWEAPON, oPC);
    if (GetIsObjectValid(oEq))
    {
        sReport = sReport + "EQ_LWEAPON:" + GetTag(oEq) + ",";
    }
    oEq = GetItemInSlot(INVENTORY_SLOT_LEFTARM, oPC);
    if (GetIsObjectValid(oEq))
    {
        sReport = sReport + "EQ_LARM:" + GetTag(oEq) + ",";
    }
    oEq = GetItemInSlot(INVENTORY_SLOT_RIGHTARM, oPC);
    if (GetIsObjectValid(oEq))
    {
        sReport = sReport + "EQ_RARM:" + GetTag(oEq) + ",";
    }
    oEq = GetItemInSlot(INVENTORY_SLOT_IMPLANT, oPC);
    if (GetIsObjectValid(oEq))
    {
        sReport = sReport + "EQ_IMPLANT:" + GetTag(oEq) + ",";
    }
    oEq = GetItemInSlot(INVENTORY_SLOT_BELT, oPC);
    if (GetIsObjectValid(oEq))
    {
        sReport = sReport + "EQ_BELT:" + GetTag(oEq) + ",";
    }

    KSE_Diag(26, sReport);
}

// DeathLink outgoing half. Same stateless design as everything else here --
// just honestly reports whether the PC is currently dead every poll, no
// in-game persistence or edge-detection. The client is authoritative on
// dedup (only bounce one DeathLink per death, reset once alive again) since
// custom globals don't persist across saves/reloads and this event will
// otherwise repeat every single poll for as long as the player stays dead.
void CheckDeath()
{
    object oPC = GetFirstPC();
    if (GetIsDead(oPC))
    {
        KSE_Diag(64, "AP|CHECK|DEATH");
    }
}

// Light/dark alignment, reported every poll -- same stateless design as
// everything else here. GetGoodEvilValue is 0 (full dark) to 100 (full
// light), 50 neutral. The client tracks the last-known value itself and
// derives newly-crossed 10-point thresholds (and the True Neutral/Fallen
// Jedi/Redeemed Sith bonus checks, which need a bit of history) -- see
// kotor_location_tracker.py.
void CheckAlignment()
{
    object oPC = GetFirstPC();
    KSE_Diag(83, "AP|ALIGNMENT|" + IntToString(GetGoodEvilValue(oPC)));
}

// Goal detection: STA_MALAK_DEAD is a real, pre-declared globalcat.2da
// Boolean, set unconditionally true in sta_m45ad across every narrative
// branch of Malak's death (k_psta_mlkend/k_psta_ud_malak and its _mal2-8
// variants) and never reset -- same proven detection shape as the _DONE
// quest flags above, just not sharing their naming convention so it isn't
// swept up by the generic *_DONE scan. Reported unconditionally once true,
// same stateless design as everything else here -- the client decides what
// to do with it (only the defeat_malak Goal option cares).
void CheckGoal()
{
    if (GetGlobalBoolean("STA_MALAK_DEAD"))
    {
        KSE_Diag(84, "AP|CHECK|GOAL|MALAK_DEAD");
    }
}

// Character level, for the max_level Goal option. GetHitDice returns total
// character level regardless of class/multiclass split -- exactly the same
// number exptable.2da's cumulative XP thresholds are keyed on.
void CheckLevel()
{
    object oPC = GetFirstPC();
    KSE_Diag(85, "AP|LEVELREPORT|" + IntToString(GetHitDice(oPC)));
}

void main()
{
    CheckQuests();
    CheckPlot();
    CheckJournal();
    CheckXP();
    CheckCredits();
    CheckInventory();
    CheckAbilityScores();
    CheckClasses();
    CheckFeats();
    CheckForcePowers();
    CheckCharacterName();
    CheckSkills();
    CheckDeath();
    CheckAlignment();
    CheckGoal();
    CheckLevel();

    // Self-healing heartbeat restart, staleness-based (not a one-shot flag).
    // Confirmed this session: a same-process in-game Load Game silently kills
    // the heartbeat's DelayCommand chain while leaving KSE's in-session data
    // store untouched (that store is DLL-memory, tied to the process, not the
    // save) -- so a one-shot "hb_started" flag that's only ever SET, never
    // cleared, can never detect that case: it stays true forever after the
    // first start, even once the actual heartbeat is dead. Fixed by having
    // Tick() stamp the current time into KSE data on every tick, and treating
    // the heartbeat as dead if that stamp is missing OR older than 20s (4x
    // the 5s tick interval, generous slack for scheduling jitter). This also
    // replaces hb_started entirely -- covers first-ever start (no stamp yet),
    // full process restart (KSE store wiped, no stamp), and a same-process
    // Load Game (stamp present but stale) with the same single check.
    int nNow = GetTimeHour() * 3600 + GetTimeMinute() * 60 + GetTimeSecond();
    int nHeartbeatDead = 1;
    if (KSE_HasData("hb_tick_time"))
    {
        int nLastTick = StringToInt(KSE_GetData("hb_tick_time"));
        int nDelta = nNow - nLastTick;
        if (nDelta < 0) nDelta = nDelta + 86400; // midnight wraparound
        if (nDelta < 20) nHeartbeatDead = 0;
    }
    if (nHeartbeatDead)
    {
        // Stamp immediately, before the new heartbeat's own first tick runs --
        // otherwise a second poll_shared call arriving moments later (e.g. a
        // module-load and an area-enter firing back to back) would still see
        // a stale/missing stamp and spawn a SECOND heartbeat, double-ticking
        // everything from then on.
        KSE_SetData("hb_tick_time", IntToString(nNow));
        ExecuteScript("ap_heartbeat", OBJECT_SELF);
    }
}
