// Additional Enemies bounty-card drop. Generated by
// scripts/patch_additional_enemies.py -- one of these per module, cloned
// onto exactly one of that module's newly-placed enemies. Preserves the
// original creature's own OnDeath (k_def_death01) by
// calling it first, then adds the bounty card on top.
#include "kse"

void main()
{
    ExecuteScript("k_def_death01", OBJECT_SELF);
    CreateItemOnObject("ap_bounty_card", OBJECT_SELF, 1);
    KSE_Diag(152, "AP|BOUNTY|DROPPED");
}
