// Item-pickup wrapper -- runs tat_m18aa's real vanilla
// Mod_OnAcquirItem script (k_ptat18aa_acqui, preserved as apo_k_ptat18aa_acqui_orig)
// first, then applies this seed's pickup-handling mode.
#include "kse"

void HandleAcquiredItem()
{
    object oItem = GetModuleItemAcquired();
    if (GetLocalBoolean(oItem, 0)) return;
    string sTag = GetStringLowerCase(GetTag(oItem));
    if (KSE_HasData("granted_exempt_" + sTag)) return;
    if (sTag == "bast_temp_saber" ||
        sTag == "carth_temp_gun" ||
        sTag == "dan13_bluesaber" ||
        sTag == "dan13_goldsaber" ||
        sTag == "dan13_goldsabler" ||
        sTag == "dan13_grnsaber" ||
        sTag == "dan13_practice" ||
        sTag == "dan14_nothing" ||
        sTag == "dan_mine_prop" ||
        sTag == "duronjournal" ||
        sTag == "end_1damblast" ||
        sTag == "end_onedam" ||
        sTag == "flash_gren" ||
        sTag == "g1_a_class5001" ||
        sTag == "g1_a_class5002" ||
        sTag == "g1_a_class6001" ||
        sTag == "g1_a_class8001" ||
        sTag == "g1_i_belt001" ||
        sTag == "g1_i_drdcomspk01" ||
        sTag == "g1_i_drdhvplat01" ||
        sTag == "g1_i_drdshld001" ||
        sTag == "g1_i_drdutldev01" ||
        sTag == "g1_i_drdutldev02" ||
        sTag == "g1_i_drdutldev03" ||
        sTag == "g1_i_gauntlet01" ||
        sTag == "g1_i_implant301" ||
        sTag == "g1_i_implant302" ||
        sTag == "g1_i_implant303" ||
        sTag == "g1_i_implant304" ||
        sTag == "g1_i_mask01" ||
        sTag == "g1_i_mask02" ||
        sTag == "g1_i_mask03" ||
        sTag == "g1_w_dblsbr001" ||
        sTag == "g1_w_dblsbr002" ||
        sTag == "g1_w_dsrptrfl001" ||
        sTag == "g1_w_hvrptbltr01" ||
        sTag == "g1_w_ionrfl01" ||
        sTag == "g1_w_lghtsbr01" ||
        sTag == "g1_w_lghtsbr02" ||
        sTag == "g1_w_rptnblstr01" ||
        sTag == "g1_w_sbrcrstl20" ||
        sTag == "g1_w_sbrcrstl21" ||
        sTag == "g1_w_shortsbr01" ||
        sTag == "g1_w_shortsbr02" ||
        sTag == "g1_w_vbroswrd01" ||
        sTag == "g_a_class4001" ||
        sTag == "g_a_class4002" ||
        sTag == "g_a_class4003" ||
        sTag == "g_a_class4004" ||
        sTag == "g_a_class4005" ||
        sTag == "g_a_class4006" ||
        sTag == "g_a_class4007" ||
        sTag == "g_a_class4008" ||
        sTag == "g_a_class4009" ||
        sTag == "g_a_class5001" ||
        sTag == "g_a_class5002" ||
        sTag == "g_a_class5003" ||
        sTag == "g_a_class5004" ||
        sTag == "g_a_class5005" ||
        sTag == "g_a_class5006" ||
        sTag == "g_a_class5007" ||
        sTag == "g_a_class5008" ||
        sTag == "g_a_class5009" ||
        sTag == "g_a_class5010" ||
        sTag == "g_a_class6001" ||
        sTag == "g_a_class6002" ||
        sTag == "g_a_class6003" ||
        sTag == "g_a_class6004" ||
        sTag == "g_a_class6005" ||
        sTag == "g_a_class6006" ||
        sTag == "g_a_class6007" ||
        sTag == "g_a_class6008" ||
        sTag == "g_a_class6009" ||
        sTag == "g_a_class7001" ||
        sTag == "g_a_class7002" ||
        sTag == "g_a_class7003" ||
        sTag == "g_a_class7004" ||
        sTag == "g_a_class7005" ||
        sTag == "g_a_class7006" ||
        sTag == "g_a_class8001" ||
        sTag == "g_a_class8002" ||
        sTag == "g_a_class8003" ||
        sTag == "g_a_class8004" ||
        sTag == "g_a_class8005" ||
        sTag == "g_a_class8006" ||
        sTag == "g_a_class8007" ||
        sTag == "g_a_class8009" ||
        sTag == "g_a_class9001" ||
        sTag == "g_a_class9002" ||
        sTag == "g_a_class9003" ||
        sTag == "g_a_class9004" ||
        sTag == "g_a_class9005" ||
        sTag == "g_a_class9006" ||
        sTag == "g_a_class9007" ||
        sTag == "g_a_class9009" ||
        sTag == "g_a_class9010" ||
        sTag == "g_a_class9011" ||
        sTag == "g_a_clothes01" ||
        sTag == "g_a_clothes02" ||
        sTag == "g_a_clothes03" ||
        sTag == "g_a_clothes04" ||
        sTag == "g_a_clothes05" ||
        sTag == "g_a_clothes06" ||
        sTag == "g_a_clothes07" ||
        sTag == "g_a_clothes08" ||
        sTag == "g_a_clothes09" ||
        sTag == "g_a_jedirobe002" ||
        sTag == "g_a_jedirobe003" ||
        sTag == "g_a_jedirobe007" ||
        sTag == "g_a_jedirobe01" ||
        sTag == "g_a_jedirobe02" ||
        sTag == "g_a_jedirobe03" ||
        sTag == "g_a_jedirobe04" ||
        sTag == "g_a_jedirobe05" ||
        sTag == "g_a_jedirobe06" ||
        sTag == "g_a_kghtrobe01" ||
        sTag == "g_a_kghtrobe02" ||
        sTag == "g_a_kghtrobe03" ||
        sTag == "g_a_kghtrobe04" ||
        sTag == "g_a_kghtrobe05" ||
        sTag == "g_a_mstrrobe01" ||
        sTag == "g_a_mstrrobe02" ||
        sTag == "g_a_mstrrobe03" ||
        sTag == "g_a_mstrrobe04" ||
        sTag == "g_a_mstrrobe05" ||
        sTag == "g_a_mstrrobe06" ||
        sTag == "g_a_mstrrobe07" ||
        sTag == "g_band" ||
        sTag == "g_i_adrnaline001" ||
        sTag == "g_i_adrnaline002" ||
        sTag == "g_i_adrnaline003" ||
        sTag == "g_i_adrnaline004" ||
        sTag == "g_i_adrnaline005" ||
        sTag == "g_i_adrnaline006" ||
        sTag == "g_i_asthitem001" ||
        sTag == "g_i_belt001" ||
        sTag == "g_i_belt002" ||
        sTag == "g_i_belt003" ||
        sTag == "g_i_belt004" ||
        sTag == "g_i_belt005" ||
        sTag == "g_i_belt006" ||
        sTag == "g_i_belt007" ||
        sTag == "g_i_belt008" ||
        sTag == "g_i_belt009" ||
        sTag == "g_i_belt010" ||
        sTag == "g_i_belt011" ||
        sTag == "g_i_belt012" ||
        sTag == "g_i_belt013" ||
        sTag == "g_i_belt014" ||
        sTag == "g_i_bithitem001" ||
        sTag == "g_i_bithitem002" ||
        sTag == "g_i_bithitem003" ||
        sTag == "g_i_bithitem004" ||
        sTag == "g_i_cmbtshot001" ||
        sTag == "g_i_cmbtshot002" ||
        sTag == "g_i_cmbtshot003" ||
        sTag == "g_i_collarlgt001" ||
        sTag == "g_i_credits001" ||
        sTag == "g_i_credits002" ||
        sTag == "g_i_credits003" ||
        sTag == "g_i_credits004" ||
        sTag == "g_i_credits005" ||
        sTag == "g_i_credits006" ||
        sTag == "g_i_credits007" ||
        sTag == "g_i_credits008" ||
        sTag == "g_i_credits009" ||
        sTag == "g_i_credits010" ||
        sTag == "g_i_credits011" ||
        sTag == "g_i_credits012" ||
        sTag == "g_i_credits013" ||
        sTag == "g_i_credits014" ||
        sTag == "g_i_credits015" ||
        sTag == "g_i_credits016" ||
        sTag == "g_i_credits017" ||
        sTag == "g_i_crhide001" ||
        sTag == "g_i_crhide002" ||
        sTag == "g_i_crhide003" ||
        sTag == "g_i_crhide004" ||
        sTag == "g_i_crhide005" ||
        sTag == "g_i_crhide006" ||
        sTag == "g_i_crhide007" ||
        sTag == "g_i_crhide008" ||
        sTag == "g_i_crhide009" ||
        sTag == "g_i_crhide010" ||
        sTag == "g_i_crhide011" ||
        sTag == "g_i_crhide012" ||
        sTag == "g_i_crhide013" ||
        sTag == "g_i_datapad001" ||
        sTag == "g_i_drdcomspk001" ||
        sTag == "g_i_drdcomspk002" ||
        sTag == "g_i_drdcomspk003" ||
        sTag == "g_i_drdhvplat001" ||
        sTag == "g_i_drdhvplat002" ||
        sTag == "g_i_drdhvplat003" ||
        sTag == "g_i_drdltplat001" ||
        sTag == "g_i_drdltplat002" ||
        sTag == "g_i_drdltplat003" ||
        sTag == "g_i_drdmdplat001" ||
        sTag == "g_i_drdmdplat002" ||
        sTag == "g_i_drdmdplat003" ||
        sTag == "g_i_drdmtnsen001" ||
        sTag == "g_i_drdmtnsen002" ||
        sTag == "g_i_drdmtnsen003" ||
        sTag == "g_i_drdrepeqp001" ||
        sTag == "g_i_drdrepeqp002" ||
        sTag == "g_i_drdrepeqp003" ||
        sTag == "g_i_drdsecspk001" ||
        sTag == "g_i_drdsecspk002" ||
        sTag == "g_i_drdsecspk003" ||
        sTag == "g_i_drdshld001" ||
        sTag == "g_i_drdshld002" ||
        sTag == "g_i_drdshld003" ||
        sTag == "g_i_drdshld005" ||
        sTag == "g_i_drdshld006" ||
        sTag == "g_i_drdshld007" ||
        sTag == "g_i_drdshld008" ||
        sTag == "g_i_drdsncsen001" ||
        sTag == "g_i_drdsncsen002" ||
        sTag == "g_i_drdsncsen003" ||
        sTag == "g_i_drdsrcscp001" ||
        sTag == "g_i_drdsrcscp002" ||
        sTag == "g_i_drdsrcscp003" ||
        sTag == "g_i_drdtrgcom001" ||
        sTag == "g_i_drdtrgcom002" ||
        sTag == "g_i_drdtrgcom003" ||
        sTag == "g_i_drdtrgcom004" ||
        sTag == "g_i_drdtrgcom005" ||
        sTag == "g_i_drdtrgcom006" ||
        sTag == "g_i_drdutldev001" ||
        sTag == "g_i_drdutldev002" ||
        sTag == "g_i_drdutldev003" ||
        sTag == "g_i_drdutldev004" ||
        sTag == "g_i_drdutldev005" ||
        sTag == "g_i_drdutldev006" ||
        sTag == "g_i_drdutldev007" ||
        sTag == "g_i_drdutldev008" ||
        sTag == "g_i_drdutldev009" ||
        sTag == "g_i_drdutldev010" ||
        sTag == "g_i_drdutldev011" ||
        sTag == "g_i_drdutldev012" ||
        sTag == "g_i_frarmbnds01" ||
        sTag == "g_i_frarmbnds010" ||
        sTag == "g_i_frarmbnds02" ||
        sTag == "g_i_frarmbnds03" ||
        sTag == "g_i_frarmbnds04" ||
        sTag == "g_i_frarmbnds05" ||
        sTag == "g_i_frarmbnds06" ||
        sTag == "g_i_frarmbnds07" ||
        sTag == "g_i_frarmbnds08" ||
        sTag == "g_i_frarmbnds09" ||
        sTag == "g_i_frarmbnds10" ||
        sTag == "g_i_frarmbnds11" ||
        sTag == "g_i_frarmbnds12" ||
        sTag == "g_i_frarmbnds13" ||
        sTag == "g_i_frarmbnds14" ||
        sTag == "g_i_frarmbnds15" ||
        sTag == "g_i_frarmbnds16" ||
        sTag == "g_i_frarmbnds17" ||
        sTag == "g_i_frarmbnds18" ||
        sTag == "g_i_frarmbnds19" ||
        sTag == "g_i_frarmbnds20" ||
        sTag == "g_i_frarmbnds21" ||
        sTag == "g_i_gauntlet01" ||
        sTag == "g_i_gauntlet02" ||
        sTag == "g_i_gauntlet03" ||
        sTag == "g_i_gauntlet04" ||
        sTag == "g_i_gauntlet05" ||
        sTag == "g_i_gauntlet06" ||
        sTag == "g_i_gauntlet07" ||
        sTag == "g_i_gauntlet08" ||
        sTag == "g_i_gauntlet09" ||
        sTag == "g_i_glowrod01" ||
        sTag == "g_i_implant101" ||
        sTag == "g_i_implant102" ||
        sTag == "g_i_implant103" ||
        sTag == "g_i_implant104" ||
        sTag == "g_i_implant201" ||
        sTag == "g_i_implant202" ||
        sTag == "g_i_implant203" ||
        sTag == "g_i_implant204" ||
        sTag == "g_i_implant301" ||
        sTag == "g_i_implant302" ||
        sTag == "g_i_implant303" ||
        sTag == "g_i_implant304" ||
        sTag == "g_i_implant305" ||
        sTag == "g_i_implant306" ||
        sTag == "g_i_implant307" ||
        sTag == "g_i_implant308" ||
        sTag == "g_i_implant309" ||
        sTag == "g_i_implant310" ||
        sTag == "g_i_mask009" ||
        sTag == "g_i_mask01" ||
        sTag == "g_i_mask02" ||
        sTag == "g_i_mask023" ||
        sTag == "g_i_mask03" ||
        sTag == "g_i_mask04" ||
        sTag == "g_i_mask05" ||
        sTag == "g_i_mask06" ||
        sTag == "g_i_mask07" ||
        sTag == "g_i_mask08" ||
        sTag == "g_i_mask09" ||
        sTag == "g_i_mask10" ||
        sTag == "g_i_mask11" ||
        sTag == "g_i_mask12" ||
        sTag == "g_i_mask13" ||
        sTag == "g_i_mask14" ||
        sTag == "g_i_mask15" ||
        sTag == "g_i_mask16" ||
        sTag == "g_i_mask17" ||
        sTag == "g_i_mask18" ||
        sTag == "g_i_mask19" ||
        sTag == "g_i_mask20" ||
        sTag == "g_i_mask21" ||
        sTag == "g_i_mask22" ||
        sTag == "g_i_mask23" ||
        sTag == "g_i_mask24" ||
        sTag == "g_i_medeqpmnt002" ||
        sTag == "g_i_medeqpmnt003" ||
        sTag == "g_i_medeqpmnt01" ||
        sTag == "g_i_medeqpmnt02" ||
        sTag == "g_i_medeqpmnt03" ||
        sTag == "g_i_medeqpmnt04" ||
        sTag == "g_i_medeqpmnt05" ||
        sTag == "g_i_medeqpmnt06" ||
        sTag == "g_i_medeqpmnt07" ||
        sTag == "g_i_medeqpmnt08" ||
        sTag == "g_i_parts01" ||
        sTag == "g_i_pazcard_001" ||
        sTag == "g_i_pazcard_002" ||
        sTag == "g_i_pazcard_003" ||
        sTag == "g_i_pazcard_004" ||
        sTag == "g_i_pazcard_005" ||
        sTag == "g_i_pazcard_006" ||
        sTag == "g_i_pazcard_007" ||
        sTag == "g_i_pazcard_008" ||
        sTag == "g_i_pazcard_009" ||
        sTag == "g_i_pazcard_010" ||
        sTag == "g_i_pazcard_011" ||
        sTag == "g_i_pazcard_012" ||
        sTag == "g_i_pazcard_013" ||
        sTag == "g_i_pazcard_014" ||
        sTag == "g_i_pazcard_015" ||
        sTag == "g_i_pazcard_016" ||
        sTag == "g_i_pazcard_017" ||
        sTag == "g_i_pazcard_018" ||
        sTag == "g_i_progspike002" ||
        sTag == "g_i_progspike003" ||
        sTag == "g_i_progspike01" ||
        sTag == "g_i_progspike02" ||
        sTag == "g_i_recordrod01" ||
        sTag == "g_i_secspike01" ||
        sTag == "g_i_secspike02" ||
        sTag == "g_i_torch01" ||
        sTag == "g_i_trapkit001" ||
        sTag == "g_i_trapkit002" ||
        sTag == "g_i_trapkit003" ||
        sTag == "g_i_trapkit004" ||
        sTag == "g_i_trapkit005" ||
        sTag == "g_i_trapkit006" ||
        sTag == "g_i_trapkit007" ||
        sTag == "g_i_trapkit008" ||
        sTag == "g_i_trapkit009" ||
        sTag == "g_i_trapkit01" ||
        sTag == "g_i_trapkit010" ||
        sTag == "g_i_trapkit011" ||
        sTag == "g_i_trapkit012" ||
        sTag == "g_i_trapkit02" ||
        sTag == "g_i_trapkit03" ||
        sTag == "g_i_trapkit04" ||
        sTag == "g_manaanvis" ||
        sTag == "g_scijournal" ||
        sTag == "g_unk_rancorclaw" ||
        sTag == "g_w_adhsvgren001" ||
        sTag == "g_w_blstrcrbn001" ||
        sTag == "g_w_blstrcrbn002" ||
        sTag == "g_w_blstrcrbn003" ||
        sTag == "g_w_blstrcrbn004" ||
        sTag == "g_w_blstrcrbn005" ||
        sTag == "g_w_blstrcrbn006" ||
        sTag == "g_w_blstrcrbn007" ||
        sTag == "g_w_blstrcrbn008" ||
        sTag == "g_w_blstrcrbn009" ||
        sTag == "g_w_blstrcrbn020" ||
        sTag == "g_w_blstrpstl001" ||
        sTag == "g_w_blstrpstl002" ||
        sTag == "g_w_blstrpstl003" ||
        sTag == "g_w_blstrpstl004" ||
        sTag == "g_w_blstrpstl005" ||
        sTag == "g_w_blstrpstl006" ||
        sTag == "g_w_blstrpstl007" ||
        sTag == "g_w_blstrpstl008" ||
        sTag == "g_w_blstrpstl009" ||
        sTag == "g_w_blstrpstl010" ||
        sTag == "g_w_blstrpstl020" ||
        sTag == "g_w_blstrrfl001" ||
        sTag == "g_w_blstrrfl002" ||
        sTag == "g_w_blstrrfl003" ||
        sTag == "g_w_blstrrfl004" ||
        sTag == "g_w_blstrrfl005" ||
        sTag == "g_w_blstrrfl006" ||
        sTag == "g_w_blstrrfl007" ||
        sTag == "g_w_blstrrfl008" ||
        sTag == "g_w_blstrrfl009" ||
        sTag == "g_w_blstrrfl020" ||
        sTag == "g_w_bowcstr001" ||
        sTag == "g_w_bowcstr002" ||
        sTag == "g_w_bowcstr003" ||
        sTag == "g_w_crgore001" ||
        sTag == "g_w_crgore002" ||
        sTag == "g_w_crslash001" ||
        sTag == "g_w_crslash002" ||
        sTag == "g_w_crslash003" ||
        sTag == "g_w_crslash004" ||
        sTag == "g_w_crslash005" ||
        sTag == "g_w_crslash006" ||
        sTag == "g_w_crslash007" ||
        sTag == "g_w_crslash008" ||
        sTag == "g_w_crslash009" ||
        sTag == "g_w_crslash010" ||
        sTag == "g_w_crslash011" ||
        sTag == "g_w_crslash012" ||
        sTag == "g_w_crslprc001" ||
        sTag == "g_w_crslprc002" ||
        sTag == "g_w_crslprc003" ||
        sTag == "g_w_crslprc004" ||
        sTag == "g_w_crslprc005" ||
        sTag == "g_w_cryobgren001" ||
        sTag == "g_w_dblsbr001" ||
        sTag == "g_w_dblsbr002" ||
        sTag == "g_w_dblsbr003" ||
        sTag == "g_w_dblsbr004" ||
        sTag == "g_w_dblsbr005" ||
        sTag == "g_w_dblsbr006" ||
        sTag == "g_w_dblsbr007" ||
        sTag == "g_w_dblswrd001" ||
        sTag == "g_w_dblswrd002" ||
        sTag == "g_w_dblswrd003" ||
        sTag == "g_w_dblswrd005" ||
        sTag == "g_w_drkjdisbr001" ||
        sTag == "g_w_drkjdisbr002" ||
        sTag == "g_w_dsrptpstl001" ||
        sTag == "g_w_dsrptpstl002" ||
        sTag == "g_w_dsrptrfl001" ||
        sTag == "g_w_dsrptrfl002" ||
        sTag == "g_w_firegren001" ||
        sTag == "g_w_flashgren001" ||
        sTag == "g_w_fraggren01" ||
        sTag == "g_w_gaffi001" ||
        sTag == "g_w_hldoblstr003" ||
        sTag == "g_w_hldoblstr004" ||
        sTag == "g_w_hldoblstr01" ||
        sTag == "g_w_hldoblstr02" ||
        sTag == "g_w_hldoblstr03" ||
        sTag == "g_w_hldoblstr04" ||
        sTag == "g_w_hvrptbltr002" ||
        sTag == "g_w_hvrptbltr01" ||
        sTag == "g_w_hvrptbltr02" ||
        sTag == "g_w_hvyblstr002" ||
        sTag == "g_w_hvyblstr01" ||
        sTag == "g_w_hvyblstr02" ||
        sTag == "g_w_hvyblstr03" ||
        sTag == "g_w_hvyblstr04" ||
        sTag == "g_w_hvyblstr05" ||
        sTag == "g_w_hvyblstr06" ||
        sTag == "g_w_hvyblstr07" ||
        sTag == "g_w_hvyblstr08" ||
        sTag == "g_w_hvyblstr09" ||
        sTag == "g_w_ionblstr01" ||
        sTag == "g_w_ionblstr02" ||
        sTag == "g_w_iongren01" ||
        sTag == "g_w_ionrfl01" ||
        sTag == "g_w_ionrfl02" ||
        sTag == "g_w_ionrfl03" ||
        sTag == "g_w_lghtsbr002" ||
        sTag == "g_w_lghtsbr007" ||
        sTag == "g_w_lghtsbr008" ||
        sTag == "g_w_lghtsbr01" ||
        sTag == "g_w_lghtsbr012" ||
        sTag == "g_w_lghtsbr02" ||
        sTag == "g_w_lghtsbr03" ||
        sTag == "g_w_lghtsbr04" ||
        sTag == "g_w_lghtsbr05" ||
        sTag == "g_w_lghtsbr06" ||
        sTag == "g_w_lngswrd01" ||
        sTag == "g_w_lngswrd02" ||
        sTag == "g_w_lngswrd03" ||
        sTag == "g_w_null001" ||
        sTag == "g_w_null002" ||
        sTag == "g_w_null003" ||
        sTag == "g_w_null004" ||
        sTag == "g_w_null005" ||
        sTag == "g_w_null006" ||
        sTag == "g_w_null007" ||
        sTag == "g_w_poisngren01" ||
        sTag == "g_w_qtrstaff01" ||
        sTag == "g_w_qtrstaff02" ||
        sTag == "g_w_qtrstaff03" ||
        sTag == "g_w_rptnblstr004" ||
        sTag == "g_w_rptnblstr01" ||
        sTag == "g_w_rptnblstr02" ||
        sTag == "g_w_rptnblstr03" ||
        sTag == "g_w_sbrcrstl01" ||
        sTag == "g_w_sbrcrstl015" ||
        sTag == "g_w_sbrcrstl02" ||
        sTag == "g_w_sbrcrstl03" ||
        sTag == "g_w_sbrcrstl04" ||
        sTag == "g_w_sbrcrstl05" ||
        sTag == "g_w_sbrcrstl06" ||
        sTag == "g_w_sbrcrstl07" ||
        sTag == "g_w_sbrcrstl08" ||
        sTag == "g_w_sbrcrstl09" ||
        sTag == "g_w_sbrcrstl10" ||
        sTag == "g_w_sbrcrstl11" ||
        sTag == "g_w_sbrcrstl12" ||
        sTag == "g_w_sbrcrstl13" ||
        sTag == "g_w_sbrcrstl14" ||
        sTag == "g_w_sbrcrstl15" ||
        sTag == "g_w_sbrcrstl16" ||
        sTag == "g_w_sbrcrstl17" ||
        sTag == "g_w_sbrcrstl18" ||
        sTag == "g_w_sbrcrstl19" ||
        sTag == "g_w_shortsbr01" ||
        sTag == "g_w_shortsbr02" ||
        sTag == "g_w_shortsbr03" ||
        sTag == "g_w_shortsbr04" ||
        sTag == "g_w_shortsbr05" ||
        sTag == "g_w_shortswrd01" ||
        sTag == "g_w_shortswrd02" ||
        sTag == "g_w_shortswrd03" ||
        sTag == "g_w_sonicgren01" ||
        sTag == "g_w_sonicpstl01" ||
        sTag == "g_w_sonicpstl02" ||
        sTag == "g_w_sonicrfl01" ||
        sTag == "g_w_sonicrfl02" ||
        sTag == "g_w_sonicrfl03" ||
        sTag == "g_w_stunbaton005" ||
        sTag == "g_w_stunbaton01" ||
        sTag == "g_w_stunbaton02" ||
        sTag == "g_w_stunbaton03" ||
        sTag == "g_w_stunbaton04" ||
        sTag == "g_w_stunbaton05" ||
        sTag == "g_w_stunbaton06" ||
        sTag == "g_w_stunbaton07" ||
        sTag == "g_w_stungren01" ||
        sTag == "g_w_thermldet002" ||
        sTag == "g_w_thermldet01" ||
        sTag == "g_w_vbrdblswd01" ||
        sTag == "g_w_vbrdblswd02" ||
        sTag == "g_w_vbrdblswd03" ||
        sTag == "g_w_vbrdblswd04" ||
        sTag == "g_w_vbrdblswd05" ||
        sTag == "g_w_vbrdblswd06" ||
        sTag == "g_w_vbrdblswd07" ||
        sTag == "g_w_vbroshort002" ||
        sTag == "g_w_vbroshort01" ||
        sTag == "g_w_vbroshort02" ||
        sTag == "g_w_vbroshort03" ||
        sTag == "g_w_vbroshort04" ||
        sTag == "g_w_vbroshort05" ||
        sTag == "g_w_vbroshort06" ||
        sTag == "g_w_vbroshort07" ||
        sTag == "g_w_vbroshort08" ||
        sTag == "g_w_vbroshort09" ||
        sTag == "g_w_vbroswrd002" ||
        sTag == "g_w_vbroswrd01" ||
        sTag == "g_w_vbroswrd02" ||
        sTag == "g_w_vbroswrd03" ||
        sTag == "g_w_vbroswrd04" ||
        sTag == "g_w_vbroswrd05" ||
        sTag == "g_w_vbroswrd06" ||
        sTag == "g_w_vbroswrd07" ||
        sTag == "g_w_vbroswrd08" ||
        sTag == "g_w_waraxe001" ||
        sTag == "g_w_waraxe002" ||
        sTag == "g_w_warblade001" ||
        sTag == "g_w_warblade002" ||
        sTag == "geno_armor" ||
        sTag == "geno_blade" ||
        sTag == "geno_blaster" ||
        sTag == "geno_gloves" ||
        sTag == "geno_stealth" ||
        sTag == "geno_visor" ||
        sTag == "grarwwaar_pad" ||
        sTag == "guunjournal" ||
        sTag == "item001" ||
        sTag == "k34_itm_terahide" ||
        sTag == "k37_itm_freednf1" ||
        sTag == "k37_itm_freednf2" ||
        sTag == "k37_itm_freedont" ||
        sTag == "k39_itm_terahide" ||
        sTag == "k_kor_koltadvmed" ||
        sTag == "k_kor_koltomed" ||
        sTag == "k_kor_teranclaw2" ||
        sTag == "kas22_kinra_claw" ||
        sTag == "kas22_longsword" ||
        sTag == "kas23_baccasword" ||
        sTag == "kas24_kinra_claw" ||
        sTag == "kas24_lightsaber" ||
        sTag == "kas25_datapad1" ||
        sTag == "kas25_datapad2" ||
        sTag == "kas25_longsword" ||
        sTag == "kor33a_credit150" ||
        sTag == "kor33a_credit450" ||
        sTag == "kor33a_credit600" ||
        sTag == "kor33b_credit150" ||
        sTag == "kor33b_credit600" ||
        sTag == "kor34_credits150" ||
        sTag == "kor34_credits450" ||
        sTag == "kor34_credits600" ||
        sTag == "kor34_credits900" ||
        sTag == "kor35_credits150" ||
        sTag == "kor35_credits450" ||
        sTag == "kor36_credits150" ||
        sTag == "kor37_credits450" ||
        sTag == "kor37_droidblast" ||
        sTag == "kor38a_credit450" ||
        sTag == "kor38a_credit600" ||
        sTag == "kor38a_gauntlet" ||
        sTag == "kor38b_assassin" ||
        sTag == "kor38b_credit150" ||
        sTag == "kor38b_credit450" ||
        sTag == "kor38b_mask" ||
        sTag == "kor39_credits150" ||
        sTag == "kor39_credits450" ||
        sTag == "kor39_credits600" ||
        sTag == "kor39_credits900" ||
        sTag == "lev40_supergun" ||
        sTag == "man28_firbite" ||
        sTag == "man28_selkclaw" ||
        sTag == "placeholder01" ||
        sTag == "ptar_rakalphacla" ||
        sTag == "ptar_rakclaw" ||
        sTag == "ptar_rakghoulser" ||
        sTag == "ptar_shockstick" ||
        sTag == "punk_rancorgren" ||
        sTag == "rakatanelderhide" ||
        sTag == "shaelajournal" ||
        sTag == "sonicattachment" ||
        sTag == "sta45a_credit150" ||
        sTag == "sta45a_credit200" ||
        sTag == "sta45a_credit300" ||
        sTag == "sta45a_credits50" ||
        sTag == "sta45b_credit150" ||
        sTag == "sta45b_credit200" ||
        sTag == "sta45b_credit300" ||
        sTag == "sta45c_credit150" ||
        sTag == "sta45c_credit200" ||
        sTag == "sta45c_credit300" ||
        sTag == "sta45d_credit300" ||
        sTag == "sta_light002" ||
        sTag == "sta_light1" ||
        sTag == "sta_shortligh001" ||
        sTag == "sta_shortlight1" ||
        sTag == "sta_temp_saber" ||
        sTag == "sta_temp_saber2" ||
        sTag == "tar03_brejikband" ||
        sTag == "tar03_brejikbelt" ||
        sTag == "tar03_brejikglov" ||
        sTag == "tar05_stampyclaw" ||
        sTag == "tar05_stampyhide" ||
        sTag == "tar08_davikmask" ||
        sTag == "tar11_powerbelt" ||
        sTag == "tat18_kraytclaw" ||
        sTag == "tat20_gaffi02" ||
        sTag == "tat20_gaffistick" ||
        sTag == "tempselk" ||
        sTag == "vorndata" ||
        sTag == "w_blhvy001" ||
        sTag == "w_blhvy002" ||
        sTag == "w_bstrcrbn" ||
        sTag == "w_lghtsbr001" ||
        sTag == "w_null")
    {
        object oPC = GetFirstPC();
        int nCurCredits = GetGold(oPC);
        if (KSE_HasData("last_credits"))
        {
            int nLastCredits = StringToInt(KSE_GetData("last_credits"));
            if (nCurCredits < nLastCredits)
            {
                KSE_SetData("last_credits", IntToString(nCurCredits));
                KSE_SetData("granted_exempt_" + sTag, "1");
                return;
            }
        }
        KSE_SetData("last_credits", IntToString(nCurCredits));
        SetLocalBoolean(oItem, 0, TRUE);
        KSE_Diag(86, "AP|SUPPRESSED_ITEM|" + sTag);
        DestroyObject(oItem);
    }
}

void main()
{
    ExecuteScript("apo_k_ptat18aa_acqui_orig", OBJECT_SELF);
    HandleAcquiredItem();
}
