r"""
Packages the "always-on" base-mod Override content -- area trampolines,
the heartbeat, ap_poll_shared, companion suppression, and store-open
markers -- into dist/Override/, a ready-to-copy folder a tester can drop
straight into their own game's Override without needing Python, pykotor,
or nwnnsscomp.exe at all.

This works because most of that content is fully deterministic given the
same base game version: it's either a byte-exact copy of a real vanilla
script (extracted once, identical on every legit copy of the same game
version) or a small wrapper compiled from a fixed template with no
per-tester variation. That's what makes it safe to build once (on a dev
machine that already has the full toolchain) and just ship the resulting
bytes.

**Exception, found live 2026-08-31**: ap_poll_shared.ncs is NOT actually
seed-independent -- its content branches on loot_mode/area_randomizer
(see generate_poll_shared.py's CheckPickupCount/CheckPlanetAvailability
gating). This script bakes in whichever of those happened to be true on
THIS packager's machine at packaging time, not the eventual tester's own
seed -- the same failure shape as the _shop_stock.json bug guarded below,
just never caught for this file specifically. The copy shipped here is
now only a safe INITIAL placeholder (loot_mode=normal, area_randomizer
off unless this machine's last generated seed said otherwise) -- the real
fix is that KotorClient.py calls generate_poll_shared.py directly with
the ACTUAL connected seed's values on every Connected, overwriting
whatever setup_game.py deployed. Don't rely on this packaged copy being
correct for anyone's real seed; it only needs to be valid enough to not
crash before a first connection happens.

Item suppression and door randomization are NOT included here -- both are
seed/option-gated and are applied directly by their own scripts
(patch_item_suppression.py, patch_door_randomizer.py) against a tester's
own install, since whether they apply at all depends on that tester's
specific generated seed.

Same reasoning excludes k_pdan_makejedi.ncs/apo_makejedi_orig.ncs (the
Dantooine trial-completion suppressor, generate_makejedi_suppressor.py):
its body branches on jedi_start, exactly like ap_poll_shared.ncs above, and
is likewise regenerated by KotorClient.py on every real Connect using the
actual connected seed's value -- not shipped here at all.

Usage:
  python package_dist.py                        -- read from the default dev GAME_DIR, write to dist/Override
  python package_dist.py --game-dir "D:\...\swkotor"   -- read from a different source install
  python package_dist.py --dist-dir "C:\...\dist"      -- write somewhere other than the repo's dist/
"""
import argparse
import json
import os
import shutil
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, SCRIPT_DIR)

from generate_companion_suppressors import COMPANIONS
from generate_store_suppressors import STORES

DEFAULT_GAME_DIR = r"C:\Program Files (x86)\Steam\steamapps\common\swkotor"
MAPPING_PATH = os.path.join(REPO_ROOT, "extender", "area_trampolines", "_mapping.json")
DEFAULT_DIST_DIR = os.path.join(REPO_ROOT, "dist", "Override")

ALWAYS_ON_EXTRA = ["ap_heartbeat", "ap_poll_shared"]

# Hand-written companion-recruit guards (not generator-produced, so
# collect_expected_resrefs() can't discover them from COMPANIONS/STORES --
# found missing from dist/Override entirely on 2026-09-02, meaning every
# prior packaged release was silently shipping the pre-fix
# early-recruit-removes-companion bug). k_ptar_addcarth/k_ptar_candadd are
# the hand-patched vanilla recruit scripts; apo_carth_orig/apo_cand_orig
# are their preserved originals.
HAND_WRITTEN_EXTRA = ["k_ptar_addcarth", "apo_carth_orig", "k_ptar_candadd", "apo_cand_orig"]


def collect_expected_resrefs():
    """Every Override resref the always-on base layer needs, derived from
    the same data the generator scripts themselves use -- never hand-typed,
    so this can't silently drift out of sync with what actually gets
    generated."""
    resrefs = set(ALWAYS_ON_EXTRA) | set(HAND_WRITTEN_EXTRA)

    with open(MAPPING_PATH, encoding="utf-8") as f:
        mapping = json.load(f)
    for entry in mapping.values():
        resrefs.add(entry["onenter"])
        resrefs.add(entry["renamed"])

    for name, module, resref, npc_const, diag_code, npc_idx in COMPANIONS:
        resrefs.add(f"apo_{name}_orig")
        resrefs.add(resref)

    for idx, (module, resref) in enumerate(STORES):
        resrefs.add(f"apo_st{idx:02d}")
        resrefs.add(resref)

    return sorted(resrefs)


def _check_shop_stock_clean():
    """Real bug found live, 2026-08-29: this script copies whatever's
    CURRENTLY deployed on the dev's live game install -- it doesn't
    regenerate anything itself. If _shop_stock.json (extender/area_trampolines/)
    has any per-seed content in it when this runs (leftover from live
    testing, not reset), that content gets baked into the "always-on"
    trampolines this script copies and silently ships to EVERY tester who
    uses the documented setup_game.py path, regardless of their own seed's
    real shop randomization. Confirmed live: dist/Override's
    k_ptar_02aa_en.ncs shipped with 30 hardcoded resrefs from a leftover
    testing session. This is a loud warning, not a silent skip -- the
    operator needs to actually reset (see below) and redeploy before
    re-running this script, not just acknowledge the warning."""
    shop_stock_path = os.path.join(REPO_ROOT, "extender", "area_trampolines", "_shop_stock.json")
    if not os.path.exists(shop_stock_path):
        return
    with open(shop_stock_path, encoding="utf-8") as f:
        stock = json.load(f)
    if any(stock.get(planet) for planet in stock):
        print("=" * 70)
        print("WARNING: _shop_stock.json has real per-seed content in it right now:")
        print(f"  {shop_stock_path}")
        for planet, resrefs in stock.items():
            if resrefs:
                print(f"  {planet}: {len(resrefs)} resrefs")
        print()
        print("Copying now would bake this into the 'always-on' dist/Override")
        print("baseline and ship it to EVERY tester, regardless of their own")
        print("seed's real shop randomization -- this exact bug shipped once")
        print("already (2026-08-26). Reset it first:")
        print('  echo {} > "' + shop_stock_path + '"')
        print("  python generate_trampoline_batch.py --all")
        print("  (redeploy the regenerated .ncs files to your live game's Override,")
        print("   e.g. via arm_orchestrator.py --area=<any area you're testing in>,")
        print("   or just copy extender/area_trampolines/*.ncs over yourself)")
        print("then re-run this script.")
        print("=" * 70)
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--game-dir", default=DEFAULT_GAME_DIR,
                         help="Source install to copy already-compiled .ncs files FROM (a dev machine with everything already generated).")
    parser.add_argument("--dist-dir", default=DEFAULT_DIST_DIR,
                         help="Where to write the packaged Override folder (default: repo's dist/Override).")
    args = parser.parse_args()

    _check_shop_stock_clean()

    source_override = os.path.join(args.game_dir, "Override")
    resrefs = collect_expected_resrefs()
    print(f"Expecting {len(resrefs)} files from {source_override}")

    os.makedirs(args.dist_dir, exist_ok=True)
    copied = 0
    missing = []
    for resref in resrefs:
        src = os.path.join(source_override, f"{resref}.ncs")
        if not os.path.exists(src):
            missing.append(resref)
            continue
        shutil.copy2(src, os.path.join(args.dist_dir, f"{resref}.ncs"))
        copied += 1

    print(f"Copied {copied}/{len(resrefs)} files -> {args.dist_dir}")
    if missing:
        print(f"\nMISSING {len(missing)} expected file(s) -- source install is out of date, "
              f"re-run the generator scripts against it first:")
        for r in missing:
            print(f"  {r}.ncs")
        sys.exit(1)


if __name__ == "__main__":
    main()
