import typing

from BaseClasses import Location


class LocationData(typing.NamedTuple):
    id: int
    region: str = "Adventure"
    location_type: str = "journal"  # "journal", "companion", "area", "alignment",
    # "alignment_bonus", "level", or "malak_defeated" -- see
    # kotor_location_tracker.py's LocationTracker.__init__ for how each is
    # consumed; every field below is read directly from there, this is not
    # a schema this file invented independently.
    # journal: the journal tag (KOTOR's own quest identifier, e.g.
    # "dan_romance") and the stage value that means "complete" -- the
    # highest real value found for that tag across every script/dialogue
    # that actually sets it (see scripts/scan_journal_values.py and
    # scan_journal_dlg_values.py; global.jrl's own documented entries
    # turned out to be unreliable and are NOT what these are built from).
    journal_tag: str = ""
    journal_target: int = 0
    # companion: NPC_* index (nwscript.nss), fires the first time
    # CHECK|COMPANION|<idx> is seen (IsAvailableCreature true) -- the
    # client tracks 'seen companions' itself, same pattern as area visits.
    companion_idx: int = -1
    # area: covered-area index (extender/area_trampolines/_mapping.json),
    # fires the first time CHECK|AREA|<idx> is seen for that index -- an
    # exploration check, client-tracked the same way as companions.
    area_idx: int = -1
    # alignment: one of the 10 real threshold crossings (0-100, excluding 50).
    alignment_value: int = -1
    # alignment_bonus: one of the 3 history-based bonus checks ("true_neutral"/
    # "fallen_jedi"/"redeemed_sith").
    alignment_bonus: str = ""
    # level: character level 2-20 (1 is the starting value, not tracked).
    level_value: int = -1


class KotorLocation(Location):
    game: str = "KotOR"


# AUTO-GENERATED by scripts/generate_kotor_locations.py -- do not hand-edit,
# re-run the generator instead (see its docstring for why, and for a real
# incident where a version of this script that DIDN'T cover every location
# type below silently wiped 33 of them on a re-run).
#
# Seven location types, all detected the same way client-side (the game
# reports raw state every poll via CHECK|.../ALIGNMENT/LEVELREPORT events;
# the client tracks what's already been converted into a check and fires
# on first occurrence -- see kotor_location_tracker.py):
#   - journal: 100 real quest-completion checks spanning every planet
#   - companion: 9 checks, one per companion, firing when they'd first
#     become available (recruitment point reached)
#   - area: 78 checks, one per covered area, firing on first visit
#   - alignment: 10 real threshold crossings (0-100, excluding 50)
#   - alignment_bonus: 3 history-based checks (true_neutral/fallen_jedi/
#     redeemed_sith)
#   - level: character levels 2-20 (1 is the starting value)
#   - malak_defeated: one-shot, Malak's defeat
base_id = 9210000

location_table: typing.Dict[str, LocationData] = {
    "Dantooine: Dead Settler": LocationData(base_id + 0, region="Dantooine", location_type="journal", journal_tag="dan_casus", journal_target=20),
    "Dantooine: Missing Companion": LocationData(base_id + 1, region="Dantooine", location_type="journal", journal_tag="dan_companion", journal_target=36),
    "Dantooine: The Jedi Council": LocationData(base_id + 2, region="Dantooine", location_type="journal", journal_tag="dan_council", journal_target=20),
    "Dantooine: Murdered Settler": LocationData(base_id + 3, region="Dantooine", location_type="journal", journal_tag="dan_murder", journal_target=99),
    "Dantooine: Mandalorian Raiders": LocationData(base_id + 4, region="Dantooine", location_type="journal", journal_tag="dan_raiders", journal_target=40),
    "Dantooine: Sandral-Matale Feud": LocationData(base_id + 5, region="Dantooine", location_type="journal", journal_tag="dan_romance", journal_target=68),
    "Dantooine: Investigate Ruins": LocationData(base_id + 6, region="Dantooine", location_type="journal", journal_tag="dan_ruins", journal_target=20),
    "Dantooine: Jedi Trials": LocationData(base_id + 7, region="Dantooine", location_type="journal", journal_tag="dan_trials", journal_target=50),
    "Ebon Hawk: Unfinished Business": LocationData(base_id + 8, region="Ebon Hawk", location_type="journal", journal_tag="ebo46_unfinishedbusiness", journal_target=30),
    "Ebon Hawk: Dwindling Supplies": LocationData(base_id + 9, region="Ebon Hawk", location_type="journal", journal_tag="ebo_supplies", journal_target=99),
    "Ebon Hawk: The Ebon Hawk": LocationData(base_id + 10, region="Ebon Hawk", location_type="journal", journal_tag="k_ebonhawk", journal_target=1),
    "Ebon Hawk: Jagi's Challenge": LocationData(base_id + 11, region="Ebon Hawk", location_type="journal", journal_tag="k_jagi", journal_target=25),
    "Ebon Hawk: Mission's Brother": LocationData(base_id + 12, region="Ebon Hawk", location_type="journal", journal_tag="k_missbroth", journal_target=99),
    "Ebon Hawk: Pazaak Rules": LocationData(base_id + 13, region="Ebon Hawk", location_type="journal", journal_tag="k_pazaak", journal_target=99),
    "Ebon Hawk: The Trouble With Gizka": LocationData(base_id + 14, region="Ebon Hawk", location_type="journal", journal_tag="k_pebo_gizkatrouble", journal_target=30),
    "Ebon Hawk: Strange Stowaway": LocationData(base_id + 15, region="Ebon Hawk", location_type="journal", journal_tag="k_pebo_stowaway", journal_target=99),
    "Ebon Hawk: Rapid Transit System": LocationData(base_id + 16, region="Ebon Hawk", location_type="journal", journal_tag="k_rapidtransit", journal_target=99),
    "Ebon Hawk: Bastila": LocationData(base_id + 17, region="Ebon Hawk", location_type="journal", journal_tag="k_swg_bastilatalk", journal_target=100),
    "Ebon Hawk: Canderous": LocationData(base_id + 18, region="Ebon Hawk", location_type="journal", journal_tag="k_swg_canderous", journal_target=120),
    "Ebon Hawk: Carth": LocationData(base_id + 19, region="Ebon Hawk", location_type="journal", journal_tag="k_swg_carthtalk", journal_target=99),
    "Ebon Hawk: Bastila's Mother": LocationData(base_id + 20, region="Ebon Hawk", location_type="journal", journal_tag="k_swg_helenatalk", journal_target=50),
    "Ebon Hawk: HK-47": LocationData(base_id + 21, region="Ebon Hawk", location_type="journal", journal_tag="k_swg_hk47talk", journal_target=60),
    "Ebon Hawk: Jolee Bindo": LocationData(base_id + 22, region="Ebon Hawk", location_type="journal", journal_tag="k_swg_joleetalk", journal_target=99),
    "Ebon Hawk: Juhani": LocationData(base_id + 23, region="Ebon Hawk", location_type="journal", journal_tag="k_swg_juhani", journal_target=120),
    "Ebon Hawk: Threat from Xor": LocationData(base_id + 24, region="Ebon Hawk", location_type="journal", journal_tag="k_xor", journal_target=25),
    "Endar Spire: Attack on the Endar Spire": LocationData(base_id + 25, region="Endar Spire", location_type="journal", journal_tag="end_attack", journal_target=99),
    "General: The Code of the Sith": LocationData(base_id + 26, region="General", location_type="journal", journal_tag="Category000", journal_target=30),
    "General: Premium Merchant": LocationData(base_id + 27, region="General", location_type="journal", journal_tag="main_premium", journal_target=20),
    "Genoharadan: Ithorak": LocationData(base_id + 28, region="Genoharadan", location_type="journal", journal_tag="Geno_Ithorak", journal_target=99),
    "Genoharadan: Lorgal": LocationData(base_id + 29, region="Genoharadan", location_type="journal", journal_tag="Geno_Lorgal", journal_target=99),
    "Genoharadan: Rulan": LocationData(base_id + 30, region="Genoharadan", location_type="journal", journal_tag="Geno_Rulan", journal_target=99),
    "Genoharadan: Vorn": LocationData(base_id + 31, region="Genoharadan", location_type="journal", journal_tag="Geno_Vorn", journal_target=99),
    "Genoharadan: Zuulan": LocationData(base_id + 32, region="Genoharadan", location_type="journal", journal_tag="Geno_Zuulan", journal_target=100),
    "Genoharadan": LocationData(base_id + 33, region="Genoharadan", location_type="journal", journal_tag="Genoharadan", journal_target=102),
    "Kashyyyk: Honest Debt": LocationData(base_id + 34, region="Kashyyyk", location_type="journal", journal_tag="kas22_EliMatton", journal_target=80),
    "Kashyyyk: Star Map: Kashyyyk": LocationData(base_id + 35, region="Kashyyyk", location_type="journal", journal_tag="kas22_starmap", journal_target=70),
    "Kashyyyk: Chieftain in Need": LocationData(base_id + 36, region="Kashyyyk", location_type="journal", journal_tag="kas23_mainwookplot", journal_target=150),
    "Kashyyyk: A Wookiee Lost": LocationData(base_id + 37, region="Kashyyyk", location_type="journal", journal_tag="kas23_rorworr", journal_target=80),
    "Kashyyyk: Jolee's Request": LocationData(base_id + 38, region="Kashyyyk", location_type="journal", journal_tag="kas24_removepoachers", journal_target=40),
    "Kashyyyk: Tach Poaching": LocationData(base_id + 39, region="Kashyyyk", location_type="journal", journal_tag="kas24_tachpoaching", journal_target=50),
    "Kashyyyk: Hidden Hunters": LocationData(base_id + 40, region="Kashyyyk", location_type="journal", journal_tag="kas25_mandalorians", journal_target=70),
    "Korriban: A Doubting Sith": LocationData(base_id + 41, region="Korriban", location_type="journal", journal_tag="kor25_doubtsith", journal_target=50),
    "Korriban: Enter the Sith Academy": LocationData(base_id + 42, region="Korriban", location_type="journal", journal_tag="kor33_enteracademy", journal_target=50),
    "Korriban: Star Map: Korriban": LocationData(base_id + 43, region="Korriban", location_type="journal", journal_tag="kor33_findstarmap", journal_target=40),
    "Korriban: Aiding Lashowe": LocationData(base_id + 44, region="Korriban", location_type="journal", journal_tag="kor35_aidlashowe", journal_target=60),
    "Korriban: The Double-Cross": LocationData(base_id + 45, region="Korriban", location_type="journal", journal_tag="kor35_doublecross", journal_target=30),
    "Korriban: The Double-Double-Cross": LocationData(base_id + 46, region="Korriban", location_type="journal", journal_tag="kor35_doublecross2", journal_target=40),
    "Korriban: Finding Dustil": LocationData(base_id + 47, region="Korriban", location_type="journal", journal_tag="kor35_findingdustil", journal_target=40),
    "Korriban: The Mandalorian Weapons Cache": LocationData(base_id + 48, region="Korriban", location_type="journal", journal_tag="kor35_mandalorian", journal_target=60),
    "Korriban: Renegade Sith": LocationData(base_id + 49, region="Korriban", location_type="journal", journal_tag="kor35_renegadesith", journal_target=60),
    "Korriban: The Way of the Sith": LocationData(base_id + 50, region="Korriban", location_type="journal", journal_tag="kor35_waysith", journal_target=60),
    "Korriban: The Sword of Ajunta Pall": LocationData(base_id + 51, region="Korriban", location_type="journal", journal_tag="kor37_ajuntapall", journal_target=60),
    "Korriban: The Hermit in the Hills": LocationData(base_id + 52, region="Korriban", location_type="journal", journal_tag="kor38_hermit", journal_target=40),
    "Korriban: Rogue Droid": LocationData(base_id + 53, region="Korriban", location_type="journal", journal_tag="kor38_roguedroid", journal_target=50),
    "Leviathan: Captured by the Leviathan": LocationData(base_id + 54, region="Leviathan", location_type="journal", journal_tag="lev_captured", journal_target=99),
    "Manaan: Manaan Swoop Races": LocationData(base_id + 55, region="Manaan", location_type="journal", journal_tag="Man26ab_swoopraces", journal_target=80),
    "Manaan: Star Map: Manaan": LocationData(base_id + 56, region="Manaan", location_type="journal", journal_tag="man26_starmap", journal_target=40),
    "Manaan: Elora, Sunry's Wife": LocationData(base_id + 57, region="Manaan", location_type="journal", journal_tag="man_elora", journal_target=20),
    "Manaan: Republic Embassy": LocationData(base_id + 58, region="Manaan", location_type="journal", journal_tag="man_emb", journal_target=2),
    "Manaan: Firith Me the Pazaak Player": LocationData(base_id + 59, region="Manaan", location_type="journal", journal_tag="man_firith", journal_target=20),
    "Manaan: Gluupor the Rodian": LocationData(base_id + 60, region="Manaan", location_type="journal", journal_tag="man_gluupor", journal_target=20),
    "Manaan: Ignus the Hotel Owner": LocationData(base_id + 61, region="Manaan", location_type="journal", journal_tag="man_ignus", journal_target=20),
    "Manaan: Republic Hiring Mercenaries": LocationData(base_id + 62, region="Manaan", location_type="journal", journal_tag="man_merc", journal_target=20),
    "Manaan: Missing Selkath": LocationData(base_id + 63, region="Manaan", location_type="journal", journal_tag="man_missing", journal_target=48),
    "Manaan: Sunry Murder Trial": LocationData(base_id + 64, region="Manaan", location_type="journal", journal_tag="man_murder", journal_target=56),
    "Manaan: Mission for the Republic": LocationData(base_id + 65, region="Manaan", location_type="journal", journal_tag="man_planet", journal_target=75),
    "Manaan: Sunry's Story": LocationData(base_id + 66, region="Manaan", location_type="journal", journal_tag="man_sunry", journal_target=30),
    "Sith Base: The Final Confrontation": LocationData(base_id + 67, region="Sith Base", location_type="journal", journal_tag="sta_confront", journal_target=11),
    "Star Forge: A Quest for the Star Forge": LocationData(base_id + 68, region="Star Forge", location_type="journal", journal_tag="k_starforge", journal_target=75),
    "Taris: The Search for Bastila": LocationData(base_id + 69, region="Taris", location_type="journal", journal_tag="tar_bastsearch", journal_target=99),
    "Taris: Bendak's Bounty": LocationData(base_id + 70, region="Taris", location_type="journal", journal_tag="tar_bendakbounty", journal_target=99),
    "Taris: Purchasing a Droid": LocationData(base_id + 71, region="Taris", location_type="journal", journal_tag="tar_buydroid", journal_target=99),
    "Taris: Dia's Bounty": LocationData(base_id + 72, region="Taris", location_type="journal", journal_tag="tar_diabounty", journal_target=99),
    "Taris: The Duel Ring": LocationData(base_id + 73, region="Taris", location_type="journal", journal_tag="tar_duelring", journal_target=99),
    "Taris: Escaping Taris": LocationData(base_id + 74, region="Taris", location_type="journal", journal_tag="tar_escape", journal_target=99),
    "Taris: Infected Outcasts": LocationData(base_id + 75, region="Taris", location_type="journal", journal_tag="tar_infectedoutcasts", journal_target=99),
    "Taris: Largo's Bounty": LocationData(base_id + 76, region="Taris", location_type="journal", journal_tag="tar_largobounty", journal_target=99),
    "Taris: Matrik's Bounty": LocationData(base_id + 77, region="Taris", location_type="journal", journal_tag="tar_matrik", journal_target=99),
    "Taris: Invited to a Party": LocationData(base_id + 78, region="Taris", location_type="journal", journal_tag="tar_party", journal_target=1),
    "Taris: Planetary Information": LocationData(base_id + 79, region="Taris", location_type="journal", journal_tag="tar_planetinfo", journal_target=99),
    "Taris: The Promised Land": LocationData(base_id + 80, region="Taris", location_type="journal", journal_tag="tar_promisedland", journal_target=40),
    "Taris: Rakghoul Serum": LocationData(base_id + 81, region="Taris", location_type="journal", journal_tag="tar_rakghoulserum", journal_target=20),
    "Taris: A Rancor in the Sewers": LocationData(base_id + 82, region="Taris", location_type="journal", journal_tag="tar_rancor", journal_target=99),
    "Taris: Rukil's Apprentice": LocationData(base_id + 83, region="Taris", location_type="journal", journal_tag="tar_rukilapprentice", journal_target=99),
    "Taris: Selven's Bounty": LocationData(base_id + 84, region="Taris", location_type="journal", journal_tag="tar_selvenbounty", journal_target=99),
    "Taris: Inside the Vulkar Base": LocationData(base_id + 85, region="Taris", location_type="journal", journal_tag="tar_vulkarbase", journal_target=99),
    "Tatooine: Worthy of History": LocationData(base_id + 86, region="Tatooine", location_type="journal", journal_tag="Tat20aa_worthy", journal_target=30),
    "Tatooine: Star Map: Tatooine": LocationData(base_id + 87, region="Tatooine", location_type="journal", journal_tag="tat17_starmap", journal_target=90),
    "Tatooine: Fair Trade": LocationData(base_id + 88, region="Tatooine", location_type="journal", journal_tag="tat17aa_jawarescue", journal_target=80),
    "Tatooine: Middleman": LocationData(base_id + 89, region="Tatooine", location_type="journal", journal_tag="tat17aa_middleman", journal_target=70),
    "Tatooine: Droid For Sale": LocationData(base_id + 90, region="Tatooine", location_type="journal", journal_tag="tat17ad_buyinghk47", journal_target=30),
    "Tatooine: Signing Nico": LocationData(base_id + 91, region="Tatooine", location_type="journal", journal_tag="tat17ae_signingnico", journal_target=70),
    "Tatooine: Tatooine Swoop Racing": LocationData(base_id + 92, region="Tatooine", location_type="journal", journal_tag="tat17ae_swoopracing", journal_target=40),
    "Tatooine: Sand People": LocationData(base_id + 93, region="Tatooine", location_type="journal", journal_tag="tat17ag_sandbounty", journal_target=150),
    "Tatooine: Tanis Trapped": LocationData(base_id + 94, region="Tatooine", location_type="journal", journal_tag="tat18aa_tanistrapped", journal_target=90),
    "Tatooine: A Desert Hunt": LocationData(base_id + 95, region="Tatooine", location_type="journal", journal_tag="tat18ac_dragonhunt", journal_target=70),
    "Tatooine: Desert Ambush": LocationData(base_id + 96, region="Tatooine", location_type="journal", journal_tag="tat_ambush", journal_target=40),
    "Unknown World: Invisible Mandalorians": LocationData(base_id + 97, region="Unknown World", location_type="journal", journal_tag="unk_invis", journal_target=30),
    "Unknown World: Rakatan Research": LocationData(base_id + 98, region="Unknown World", location_type="journal", journal_tag="unk_research", journal_target=30),
    "Unknown World: Trapped on a Nameless World": LocationData(base_id + 99, region="Unknown World", location_type="journal", journal_tag="unk_trapped", journal_target=99),
    "Companion Recruited: Bastila Shan": LocationData(base_id + 100, region="Companions", location_type="companion", companion_idx=0),
    "Companion Recruited: Canderous Ordo": LocationData(base_id + 101, region="Companions", location_type="companion", companion_idx=1),
    "Companion Recruited: Carth Onasi": LocationData(base_id + 102, region="Companions", location_type="companion", companion_idx=2),
    "Companion Recruited: HK-47": LocationData(base_id + 103, region="Companions", location_type="companion", companion_idx=3),
    "Companion Recruited: Jolee Bindo": LocationData(base_id + 104, region="Companions", location_type="companion", companion_idx=4),
    "Companion Recruited: Juhani": LocationData(base_id + 105, region="Companions", location_type="companion", companion_idx=5),
    "Companion Recruited: Mission Vao": LocationData(base_id + 106, region="Companions", location_type="companion", companion_idx=6),
    "Companion Recruited: T3-M4": LocationData(base_id + 107, region="Companions", location_type="companion", companion_idx=7),
    "Companion Recruited: Zaalbar": LocationData(base_id + 108, region="Companions", location_type="companion", companion_idx=8),
    "Visited: Endar Spire - Command Module": LocationData(base_id + 109, region="Exploration", location_type="area", area_idx=0),
    "Visited: Endar Spire - Starboard Section": LocationData(base_id + 110, region="Exploration", location_type="area", area_idx=1),
    "Visited: Taris - South Apartments": LocationData(base_id + 111, region="Exploration", location_type="area", area_idx=2),
    "Visited: Dantooine - Jedi Enclave": LocationData(base_id + 112, region="Exploration", location_type="area", area_idx=3),
    "Visited: Dantooine - Courtyard": LocationData(base_id + 113, region="Exploration", location_type="area", area_idx=4),
    "Visited: Dantooine - Matale Grounds": LocationData(base_id + 114, region="Exploration", location_type="area", area_idx=5),
    "Visited: Dantooine - Grove": LocationData(base_id + 115, region="Exploration", location_type="area", area_idx=6),
    "Visited: Dantooine - Sandral Grounds": LocationData(base_id + 116, region="Exploration", location_type="area", area_idx=7),
    "Visited: Dantooine - Ruins": LocationData(base_id + 117, region="Exploration", location_type="area", area_idx=8),
    "Visited: Ebon Hawk (ebo_m12aa)": LocationData(base_id + 118, region="Exploration", location_type="area", area_idx=9),
    "Visited: Ebon Hawk (ebo_m41aa)": LocationData(base_id + 119, region="Exploration", location_type="area", area_idx=10),
    "Visited: Kashyyyk - Czerka Landing Port": LocationData(base_id + 120, region="Exploration", location_type="area", area_idx=11),
    "Visited: Kashyyyk - Village of Rwookrrorro": LocationData(base_id + 121, region="Exploration", location_type="area", area_idx=12),
    "Visited: Kashyyyk - Hall of the Chieftain": LocationData(base_id + 122, region="Exploration", location_type="area", area_idx=13),
    "Visited: Kashyyyk - Upper Shadowlands": LocationData(base_id + 123, region="Exploration", location_type="area", area_idx=14),
    "Visited: Kashyyyk - Lower Shadowlands": LocationData(base_id + 124, region="Exploration", location_type="area", area_idx=15),
    "Visited: Korriban - Dreshdae": LocationData(base_id + 125, region="Exploration", location_type="area", area_idx=16),
    "Visited: Korriban - Sith Academy Entrance": LocationData(base_id + 126, region="Exploration", location_type="area", area_idx=17),
    "Visited: Korriban - Shyrack Caves": LocationData(base_id + 127, region="Exploration", location_type="area", area_idx=18),
    "Visited: Korriban - Sith Academy": LocationData(base_id + 128, region="Exploration", location_type="area", area_idx=19),
    "Visited: Korriban - Valley of Dark Lords": LocationData(base_id + 129, region="Exploration", location_type="area", area_idx=20),
    "Visited: Korriban - Tomb of Ajunta Pall": LocationData(base_id + 130, region="Exploration", location_type="area", area_idx=21),
    "Visited: Korriban - Tomb of Tulak Hord": LocationData(base_id + 131, region="Exploration", location_type="area", area_idx=22),
    "Visited: Korriban - Tomb of Naga Sadow": LocationData(base_id + 132, region="Exploration", location_type="area", area_idx=23),
    "Visited: Leviathan - Prison Block": LocationData(base_id + 133, region="Exploration", location_type="area", area_idx=24),
    "Visited: Leviathan - Command Deck": LocationData(base_id + 134, region="Exploration", location_type="area", area_idx=25),
    "Visited: Leviathan - Hangar": LocationData(base_id + 135, region="Exploration", location_type="area", area_idx=26),
    "Visited: Leviathan - Bridge": LocationData(base_id + 136, region="Exploration", location_type="area", area_idx=27),
    "Visited: Yavin Station": LocationData(base_id + 137, region="Exploration", location_type="area", area_idx=28),
    "Visited: Manaan - Ahto West": LocationData(base_id + 138, region="Exploration", location_type="area", area_idx=29),
    "Visited: Manaan - Ahto East": LocationData(base_id + 139, region="Exploration", location_type="area", area_idx=30),
    "Visited: Manaan - West Central": LocationData(base_id + 140, region="Exploration", location_type="area", area_idx=31),
    "Visited: Manaan - Docking Bay": LocationData(base_id + 141, region="Exploration", location_type="area", area_idx=32),
    "Visited: Manaan - East Central": LocationData(base_id + 142, region="Exploration", location_type="area", area_idx=33),
    "Visited: Manaan - Sith Base": LocationData(base_id + 143, region="Exploration", location_type="area", area_idx=34),
    "Visited: Manaan - Hrakert Station": LocationData(base_id + 144, region="Exploration", location_type="area", area_idx=35),
    "Visited: Manaan - Sea Floor": LocationData(base_id + 145, region="Exploration", location_type="area", area_idx=36),
    "Visited: Manaan - Kolto Control": LocationData(base_id + 146, region="Exploration", location_type="area", area_idx=37),
    "Visited: Manaan - Hrakert Rift": LocationData(base_id + 147, region="Exploration", location_type="area", area_idx=38),
    "Visited: Star Forge - Deck 1": LocationData(base_id + 148, region="Exploration", location_type="area", area_idx=39),
    "Visited: Star Forge - Command Center": LocationData(base_id + 149, region="Exploration", location_type="area", area_idx=40),
    "Visited: Star Forge - Viewing Platform": LocationData(base_id + 150, region="Exploration", location_type="area", area_idx=41),
    "Visited: Taris - Upper City North": LocationData(base_id + 151, region="Exploration", location_type="area", area_idx=42),
    "Visited: Taris - Upper City South": LocationData(base_id + 152, region="Exploration", location_type="area", area_idx=43),
    "Visited: Taris - North Apartments": LocationData(base_id + 153, region="Exploration", location_type="area", area_idx=44),
    "Visited: Taris - Upper City Cantina": LocationData(base_id + 154, region="Exploration", location_type="area", area_idx=45),
    "Visited: Taris - Hideout": LocationData(base_id + 155, region="Exploration", location_type="area", area_idx=46),
    "Visited: Taris - Lower City": LocationData(base_id + 156, region="Exploration", location_type="area", area_idx=47),
    "Visited: Taris - Lower City Apartments (tar_m03ab)": LocationData(base_id + 157, region="Exploration", location_type="area", area_idx=48),
    "Visited: Taris - Lower City Apartments (tar_m03ad)": LocationData(base_id + 158, region="Exploration", location_type="area", area_idx=49),
    "Visited: Taris - Javyar's Cantina": LocationData(base_id + 159, region="Exploration", location_type="area", area_idx=50),
    "Visited: Taris - Swoop Platform": LocationData(base_id + 160, region="Exploration", location_type="area", area_idx=51),
    "Visited: Taris - Undercity": LocationData(base_id + 161, region="Exploration", location_type="area", area_idx=52),
    "Visited: Taris - Lower Sewers": LocationData(base_id + 162, region="Exploration", location_type="area", area_idx=53),
    "Visited: Taris - Upper Sewers": LocationData(base_id + 163, region="Exploration", location_type="area", area_idx=54),
    "Visited: Taris - Davik's Estate": LocationData(base_id + 164, region="Exploration", location_type="area", area_idx=55),
    "Visited: Taris - Sith Base": LocationData(base_id + 165, region="Exploration", location_type="area", area_idx=56),
    "Visited: Taris - Black Vulkar Base (tar_m10aa)": LocationData(base_id + 166, region="Exploration", location_type="area", area_idx=57),
    "Visited: Taris - Black Vulkar Base (tar_m10ab)": LocationData(base_id + 167, region="Exploration", location_type="area", area_idx=58),
    "Visited: Taris - Black Vulkar Base (tar_m10ac)": LocationData(base_id + 168, region="Exploration", location_type="area", area_idx=59),
    "Visited: Taris - Hidden Bek Base (tar_m11aa)": LocationData(base_id + 169, region="Exploration", location_type="area", area_idx=60),
    "Visited: Taris - Hidden Bek Base (tar_m11ab)": LocationData(base_id + 170, region="Exploration", location_type="area", area_idx=61),
    "Visited: Tatooine - Anchorhead": LocationData(base_id + 171, region="Exploration", location_type="area", area_idx=62),
    "Visited: Tatooine - Docking Bay": LocationData(base_id + 172, region="Exploration", location_type="area", area_idx=63),
    "Visited: Tatooine - Hunting Lodge": LocationData(base_id + 173, region="Exploration", location_type="area", area_idx=64),
    "Visited: Tatooine - Swoop Registration": LocationData(base_id + 174, region="Exploration", location_type="area", area_idx=65),
    "Visited: Tatooine - Dune Sea": LocationData(base_id + 175, region="Exploration", location_type="area", area_idx=66),
    "Visited: Tatooine - Sand People Territory": LocationData(base_id + 176, region="Exploration", location_type="area", area_idx=67),
    "Visited: Tatooine - Eastern Dune Sea": LocationData(base_id + 177, region="Exploration", location_type="area", area_idx=68),
    "Visited: Tatooine - Sand People Enclave": LocationData(base_id + 178, region="Exploration", location_type="area", area_idx=69),
    "Visited: Unknown World - Central Beach": LocationData(base_id + 179, region="Exploration", location_type="area", area_idx=70),
    "Visited: Unknown World - South Beach": LocationData(base_id + 180, region="Exploration", location_type="area", area_idx=71),
    "Visited: Unknown World - North Beach": LocationData(base_id + 181, region="Exploration", location_type="area", area_idx=72),
    "Visited: Unknown World - Temple Exterior": LocationData(base_id + 182, region="Exploration", location_type="area", area_idx=73),
    "Visited: Unknown World - Elder Settlement": LocationData(base_id + 183, region="Exploration", location_type="area", area_idx=74),
    "Visited: Unknown World - Rakatan Settlement": LocationData(base_id + 184, region="Exploration", location_type="area", area_idx=75),
    "Visited: Unknown World - Temple Main Floor": LocationData(base_id + 185, region="Exploration", location_type="area", area_idx=76),
    "Visited: Unknown World - Temple Summit": LocationData(base_id + 186, region="Exploration", location_type="area", area_idx=77),
    "Alignment: Dark Side 0": LocationData(base_id + 187, region="Character", location_type="alignment", alignment_value=0),
    "Alignment: Dark Side 10": LocationData(base_id + 188, region="Character", location_type="alignment", alignment_value=10),
    "Alignment: Dark Side 20": LocationData(base_id + 189, region="Character", location_type="alignment", alignment_value=20),
    "Alignment: Dark Side 30": LocationData(base_id + 190, region="Character", location_type="alignment", alignment_value=30),
    "Alignment: Dark Side 40": LocationData(base_id + 191, region="Character", location_type="alignment", alignment_value=40),
    "Alignment: Light Side 60": LocationData(base_id + 192, region="Character", location_type="alignment", alignment_value=60),
    "Alignment: Light Side 70": LocationData(base_id + 193, region="Character", location_type="alignment", alignment_value=70),
    "Alignment: Light Side 80": LocationData(base_id + 194, region="Character", location_type="alignment", alignment_value=80),
    "Alignment: Light Side 90": LocationData(base_id + 195, region="Character", location_type="alignment", alignment_value=90),
    "Alignment: Light Side 100": LocationData(base_id + 196, region="Character", location_type="alignment", alignment_value=100),
    "Alignment: True Neutral": LocationData(base_id + 197, region="Character", location_type="alignment_bonus", alignment_bonus="true_neutral"),
    "Alignment: Fallen Jedi": LocationData(base_id + 198, region="Character", location_type="alignment_bonus", alignment_bonus="fallen_jedi"),
    "Alignment: Redeemed Sith": LocationData(base_id + 199, region="Character", location_type="alignment_bonus", alignment_bonus="redeemed_sith"),
    "Level 2 Reached": LocationData(base_id + 200, region="Character", location_type="level", level_value=2),
    "Level 3 Reached": LocationData(base_id + 201, region="Character", location_type="level", level_value=3),
    "Level 4 Reached": LocationData(base_id + 202, region="Character", location_type="level", level_value=4),
    "Level 5 Reached": LocationData(base_id + 203, region="Character", location_type="level", level_value=5),
    "Level 6 Reached": LocationData(base_id + 204, region="Character", location_type="level", level_value=6),
    "Level 7 Reached": LocationData(base_id + 205, region="Character", location_type="level", level_value=7),
    "Level 8 Reached": LocationData(base_id + 206, region="Character", location_type="level", level_value=8),
    "Level 9 Reached": LocationData(base_id + 207, region="Character", location_type="level", level_value=9),
    "Level 10 Reached": LocationData(base_id + 208, region="Character", location_type="level", level_value=10),
    "Level 11 Reached": LocationData(base_id + 209, region="Character", location_type="level", level_value=11),
    "Level 12 Reached": LocationData(base_id + 210, region="Character", location_type="level", level_value=12),
    "Level 13 Reached": LocationData(base_id + 211, region="Character", location_type="level", level_value=13),
    "Level 14 Reached": LocationData(base_id + 212, region="Character", location_type="level", level_value=14),
    "Level 15 Reached": LocationData(base_id + 213, region="Character", location_type="level", level_value=15),
    "Level 16 Reached": LocationData(base_id + 214, region="Character", location_type="level", level_value=16),
    "Level 17 Reached": LocationData(base_id + 215, region="Character", location_type="level", level_value=17),
    "Level 18 Reached": LocationData(base_id + 216, region="Character", location_type="level", level_value=18),
    "Level 19 Reached": LocationData(base_id + 217, region="Character", location_type="level", level_value=19),
    "Level 20 Reached": LocationData(base_id + 218, region="Character", location_type="level", level_value=20),
    "Malak Defeated": LocationData(base_id + 219, region="Character", location_type="malak_defeated"),
}

location_name_to_id: typing.Dict[str, int] = {name: data.id for name, data in location_table.items()}
lookup_id_to_name: typing.Dict[int, str] = {data.id: name for name, data in location_table.items()}

# Companion personal-subplot locations (2026-09-10) -- each "Ebon Hawk: ..."
# entry below is real vanilla content gated on a SPECIFIC companion being
# an active party member when it triggers (5 confirmed directly via a
# game-wide NCS disassembly scan for IsNPCPartyMember/IsAvailableCreature
# calls co-occurring with a journal advance; the plain "Ebon Hawk:
# <Companion>" generic-banter entries included defensively -- same category
# of risk even unconfirmed, since some companion-talk scripts live in the
# game's core chitin.key BIFs rather than any module .rim this scan
# covered). Single source of truth for two consumers: Rules.py's
# companion_mode=ap_gated self-referential access-rule guard (a
# companion's own item can't be circularly placed at their own gated
# check), and __init__.py's _active_locations() companion_mode=none
# filter (these are location_type="journal", not "companion", so they
# weren't caught by that filter's original "companion" type check even
# though companions never joining at all makes them just as permanently
# uncompletable as the 9 real "Companion Recruited: ..." locations are).
# Keyed by location name -> the AP item name for the companion it needs.
COMPANION_SUBPLOT_LOCATIONS: typing.Dict[str, str] = {
    "Ebon Hawk: Bastila": "Companion: Bastila Shan",
    "Ebon Hawk: Bastila's Mother": "Companion: Bastila Shan",
    "Ebon Hawk: Canderous": "Companion: Canderous Ordo",
    "Ebon Hawk: Jagi's Challenge": "Companion: Canderous Ordo",
    "Ebon Hawk: Carth": "Companion: Carth Onasi",
    "Ebon Hawk: HK-47": "Companion: HK-47",
    "Ebon Hawk: Jolee Bindo": "Companion: Jolee Bindo",
    "Ebon Hawk: Juhani": "Companion: Juhani",
    "Ebon Hawk: Threat from Xor": "Companion: Juhani",
    "Ebon Hawk: Mission's Brother": "Companion: Mission Vao",
}
